### ISSUE TITLE
Support multiple subnets per AZ using Kubernetes AWS tags

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/kube-ingress-aws-controller#102]
As listed in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L85-L91

These tags should be added to Subnets by the cloud-admin or cluster-operator to select the Subnet in which to create the loadbalancer interfaces (kubernetes uses these for ELB creation for service type LoadBalancer):

    // TagNameSubnetInternalELB is the tag name used on a subnet to designate that
    // it should be used for internal ELBs
    const TagNameSubnetInternalELB = "kubernetes.io/role/internal-elb"

    // TagNameSubnetPublicELB is the tag name used on a subnet to designate that
    // it should be used for internet ELBs
    const TagNameSubnetPublicELB = "kubernetes.io/role/elb"

If we find public and private Subnets we should select them first by Tag and if nothing was found fall back to pick 3 sorted by name (?).

**Comment by linki** [comment]
Possible solution: https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/103

**Comment by szuecs** [comment]
Cool thanks @linki

**Comment by cmcconnell1** [comment]
Hello, 'apologies if this is the wrong place, but hitting a snag here and I don't see any mention of subnet (or how to configure for specific subnets) in the main project readme.   For this cluster, I have two worker node pools each in a different AZ.

Just want to validate the solution is:  tag the subnets as specified above by @szuecs  ?

Details:
Seem to be stuck in a loop with the following error:
```A load balancer cannot be attached to multiple subnets in the same Availability Zone```

CloudFormation logs
```
16:11:53 UTC-0800	DELETE_COMPLETE	AWS::CloudFormation::Stack	opsdev-9df4348	
16:11:52 UTC-0800	DELETE_COMPLETE	AWS::ElasticLoadBalancingV2::TargetGroup	TG	
16:11:51 UTC-0800	DELETE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::TargetGroup	TG	
16:11:51 UTC-0800	DELETE_COMPLETE	AWS::ElasticLoadBalancingV2::LoadBalancer	LB	
16:11:38 UTC-0800	DELETE_IN_PROGRESS	AWS::CloudFormation::Stack	opsdev-9df4348	The following resource(s) failed to create: [TG, LB]. . Delete requested by user.
16:11:37 UTC-0800	CREATE_FAILED	AWS::ElasticLoadBalancingV2::TargetGroup	TG	Resource creation cancelled
16:11:37 UTC-0800	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::TargetGroup	TG	Resource creation Initiated
16:11:36 UTC-0800	CREATE_FAILED	AWS::ElasticLoadBalancingV2::LoadBalancer	LB	A load balancer cannot be attached to multiple subnets in the same Availability Zone
16:11:36 UTC-0800	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::TargetGroup	TG	
16:11:36 UTC-0800	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::LoadBalancer	LB	
16:11:31 UTC-0800	CREATE_IN_PROGRESS	AWS::CloudFormation::Stack	opsdev-9df4348	User Initiated
```

Thanks

**Comment by szuecs** [comment]
@cmcconnell1 Yes tag the subnets you want to have the LoadBalancer network interfaces created in.

In general is better to open an issue and reference this PR, because I only see the notification e-mail and if I would miss it then I would not see your comment and it would be lost.
