### ISSUE TITLE
Spot Fleet support

### ISSUE THREAD

**Issue by mumoshu** [zalando-incubator/kube-ingress-aws-controller#105]
Hi, thanks as always for maintaining the great project!

Today my kube-ingress-aws-controller pod has fallen into CrashLoopBack emitting the following error:

```
$ k logs kube-ingress-aws-controller-7f7974ff58-rttsp
2017/12/06 12:17:23 starting /bin/kube-ingress-aws-controller
2017/12/06 12:17:23 instance is missing the "aws:autoscaling:groupName" tag
```

Indeed it seems to expect the EC2 instance has the tag automatically added by ASG, perhaps for gathering e.g. a list of subnets ALBs should be attached.

I'm not entirely sure how it is implemented right now but would it be possible to support running kube-ingress-aws-controller on EC2 instances managed by Spot Fleet?

**Comment by szuecs** [comment]
@mumoshu which versions of this ingress-controller  are you using?
Did you upgraded recently?

**Comment by mumoshu** [comment]
@szuecs Thanks for the response!
I've tried with the `latest` tag almost a day ago.

**Comment by mikkeloscar** [comment]
Looking [here](https://aws.amazon.com/about-aws/whats-new/2017/11/spot-fleet-can-now-auto-attach-instances-to-your-load-balancers-and-scale-down-to-0-target-capacity/) and [here](https://aws.amazon.com/blogs/aws/new-auto-scaling-for-ec2-spot-fleets/) and [here](http://docs.aws.amazon.com/cli/latest/reference/ec2/request-spot-fleet.html). It looks to me that SpotFleet behaves reverse of ASGs in the sense that you must define the Load Balancer ahead of time and attach it on creation/modification of the spot fleet. This is unlike ASG where we can just attach an existing ASG to the target group of the LB.

This essentially means we would have to modify the SpotFleet configuration when creating new ALBs, something that seems far out of scope for the ingress-controller. Hopefully I missed something, and this is easier than what I think. Would be really nice to support spot fleets.

**Comment by mikkeloscar** [comment]
With #118 this should now be supported if you tag the spot fleet instances with the right tags (see readme).

**Comment by szuecs** [comment]
@mikkeloscar @mumoshu then I will close this issue. Please reopen if it does not work with the merge from #118 .

**Comment by mikkeloscar** [comment]
@szuecs :+1: 

We are also using spot instances since months now :)
