### ISSUE TITLE
stop delete create loop caused by 2 subnets

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/kube-ingress-aws-controller#108]
If an ALB can not be created, because 2 possible subnets could be attached to the ALB, the comment
https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/102#issuecomment-350153375 shows that we get into delete create loop.

Desired behaviour: log error, delete and stop to create the ALB.

**Comment by cmcconnell1** [comment]
My bad, I should have opened an issue for this.  Thanks @szuecs
