### ISSUE TITLE
Consider also HTTP load balancers

### ISSUE THREAD

**Issue by lmineiro** [zalando-incubator/kube-ingress-aws-controller#12]
Some ingress resources can require only HTTP. This can potentially be achieved with a single ALB since skipper takes cares of the routing using the Host header.

Let's use this issue to discuss if this makes sense and share some ideas

**Comment by hjacobs** [comment]
This is definitely a requirement and needed to close https://github.com/zalando-incubator/kubernetes-on-aws/issues/169

**Comment by hjacobs** [comment]
Requirements are:

* always add an HTTP listener to every Application Load Balancer
* redirect HTTP to HTTPS by default (done by Skipper)
* allow Ingress without any SSL certificate ARN => create a new ALB with fake "empty" SSL ARN and HTTP-only listener

**Comment by Raffo** [comment]
@mikkeloscar can this be closed?

**Comment by sarnowski** [comment]
I think we still need to support hybrid pages where one part is HTTP and some more critical parts HTTPS. Think of an old-school ecommerce system where the browsing part is on HTTP and the checkout on HTTPS. Both served from the same domain.

**Comment by szuecs** [comment]
We will not work on this issue, if there is no request from people

**Comment by hjacobs** [comment]
@szuecs yes, I think we could close this as we already support HTTP to HTTPS redirection via Skipper. HTTP-only should really not be something we want to offer in 2017.
