### ISSUE TITLE
Getting 503 from ALB with example config

### ISSUE THREAD

**Issue by stevelacy** [zalando-incubator/kube-ingress-aws-controller#120]
I have a cluster on aws that I am attempting to setup with an ALB.

I setup the cluster as described with: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/kops.md
I then constructed the example: https://github.com/zalando-incubator/kube-ingress-aws-controller/tree/master/example

The ALB is correctly setup, it also works when I add a SSL ARN, and I am also using external-dns for the domains.
The issue is the requests from the ALB are not routed into the cluster correctly, instead I get a `503 Service Temporarily Unavailable` response from the ALB endpoint or the domain.

The services also have the endpoint greyed out.

<img width="676" alt="screen shot 2018-01-26 at 2 56 38 pm" src="https://user-images.githubusercontent.com/5648999/35462450-36e931a0-02a9-11e8-84dd-d2ea356997bf.png">

I've taken the entire stack down, and rebuilt the example stack a few times without any success.
Any hints?

Thanks

**Comment by szuecs** [comment]
@stevelacy The ALB does not know any POD network (it's not the same as AWS network in most cases), so this will only work if you have on your kubernetes worker nodes another layer of http proxies that implement ingress. 
For that you can use github.com/zalando/skipper as described in the example.
If you did then you should have a look with "curl -v" which proxy returns the 503 and check if the service/endpoints are reachable from a worker node.

**Comment by stevelacy** [comment]
I recreated the cluster on GCP, if I end up solving this issue I'll report back
