### ISSUE TITLE
ALB Created by Ingress but Ingress not updated with ALB Hostname

### ISSUE THREAD

**Issue by sdevang** [zalando-incubator/kube-ingress-aws-controller#122]
Hi,

I am facing an issue where ALB is created by Ingress but the Ingress is not updated with ALB's hostname.

I see following in logs.

```
2018/02/07 10:11:05 Start polling sleep 30s
2018/02/07 10:11:35 Found 1 ingresses
2018/02/07 10:11:35 Found 1 stacks
2018/02/07 10:11:35 Found 1 auto scaling groups
2018/02/07 10:11:35 Found 0 single instances
2018/02/07 10:11:35 Found 5 EC2 instances
2018/02/07 10:11:35 Have 1 models
2018/02/07 10:11:36 updated ingress default/my-nginx with DNS name "xxxxxxx-lb-1hrxddetdnqk4-xxxxxxxx.eu-west-1.elb.amazonaws.com"
2018/02/07 10:11:36 Start polling sleep 30s
```

But then i do,

```yaml
$ kubectl get ing -o yaml
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    creationTimestamp: 2018-02-06T17:25:48Z
    generation: 1
    name: my-nginx
    namespace: default
    resourceVersion: "24567402"
    selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/my-nginx
    uid: c5e34d5c-0b62-11e8-9500-028b686102d8
  spec:
    rules:
    - host: my-nginx.prod.xxxxxxx.com
      http:
        paths:
        - backend:
            serviceName: my-nginx
            servicePort: 80
  status:
    loadBalancer:
      ingress:
      - ip: <IP>
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

Any idea ?

I thought the LoadBalancer section under status would be updated with ALB's hostname once the ALB is online. Is my understanding wrong ?

Regards,
Dev

**Comment by mikkeloscar** [comment]
> I thought the LoadBalancer section under status would be updated with ALB's hostname once the ALB is online. Is my understanding wrong ?

No, your understanding is not wrong, it should add the hostname.

Where does the `<IP>` in the status section come from in your example? Do you have some other ingress controller running that could be overwriting the status field?

**Comment by sdevang** [comment]
@mikkeloscar : Here is my ingress definition file.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  namespace: default
#  annotations:
#    alb.ingress.kubernetes.io/scheme: internet-facing
#    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:935783063905:certificate/44d47605-057e-44d0-83d0-3d3c95ac8c98"
#    alb.ingress.kubernetes.io/backend-protocol: HTTPS
#    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
#    alb.ingress.kubernetes.io/tags: Environment=Prod,Team=DevOps
spec:
  rules:
  - host: gitlab.prod.xxxxxxx.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 443

Devs-MBP:prod sdevang$ kubectl get ing
NAME       HOSTS                            ADDRESS         PORTS     AGE
gitlab     gitlab.prod.xxxxxxx.com  10.10.104.103   80        4m

10.10.104.103 is the IP Address of the Kubernetes worker node where the gitlab pod is running.

**Comment by sdevang** [comment]
@mikkeloscar : I do not have any other ingress controller running.

```
kube-system   heapster-4285517626-95v7k                              1/1       Running   2          53d
kube-system   kube-dns-2514474280-1cqbb                              3/3       Running   9          7d
kube-system   kube-ingress-aws-controller-3066011435-sc2th           1/1       Running   0          17h
kube-system   kubernetes-dashboard-716739405-qzvxt                   1/1       Running   4          51d
kube-system   monitoring-grafana-2360823841-fhm8q                    1/1       Running   4          32d
kube-system   monitoring-influxdb-1498291709-q1nkb                   1/1       Running   3          53d
kube-system   skipper-ingress-5k6zh                                  1/1       Running   0          18h
kube-system   skipper-ingress-5z1x8                                  1/1       Running   0          18h
kube-system   skipper-ingress-7h31w                                  1/1       Running   0          18h
kube-system   skipper-ingress-sr06n                                  1/1       Running   0          18h
kube-system   skipper-ingress-x443b                                  1/1       Running   0          18h
kube-system   tiller-deploy-737598192-8wjhf                          1/1       Running   4          51d
```

**Comment by mikkeloscar** [comment]
Hmm, what about permissions to the API server. I would expect us to log if it fails to update the ingress resource, but maybe this is the problem? Any chance you have RBAC enabled in your cluster and the ingress-controller can't write to the Kubernetes API?

**Comment by sdevang** [comment]
@mikkeloscar : We do not have RBAC enabled in our K8 Cluster.

**Comment by szuecs** [comment]
@sdevang it has to be another ingress controller which is overriding the status field in the ingress object.
As you showed in the logs of the kube-ingress-aws-controller it found the name "xxxxxxx-lb-1hrxddetdnqk4-xxxxxxxx.eu-west-1.elb.amazonaws.com", which it will write to the status field. This controller will not do any DNS lookup nor do a call the route53.

    2018/02/07 10:11:36 updated ingress default/my-nginx with DNS name "xxxxxxx-lb-1hrxddetdnqk4-xxxxxxxx.eu-west-1.elb.amazonaws.com"

Maybe nginx is "smart" and rewrites the status field. As I see you also use skipper as ingress-controller, which is pretty cool :), as maintainer I can also say that this will not write to ingress status.
As far as I know the nginx-controller will write to the status field, so maybe someone installed it into another namespace, which you did not see!?

I hope you get it done and I am happy to help, but right now I don't see how,

**Comment by szuecs** [comment]
@sdevang did you found the issue or did you tried another solution?

**Comment by mikkeloscar** [comment]
No response, closing for now.
