### ISSUE TITLE
Problem launching ingress controller in a kops cluster

### ISSUE THREAD

**Issue by itselavia** [zalando-incubator/kube-ingress-aws-controller#124]
Facing issues with following two commands in the steps mentioned for kops cluster:

1. aws ec2 authorize-security-group-ingress --group-id $sgidnode --protocol all --port -1 --source-group $sgidingress
Error: An error occurred (InvalidGroup.NotFound) when calling the AuthorizeSecurityGroupIngress operation: You have specified two resources that belong to different networks.

2. aws ec2 create-tags --resources $sgidingress --tags "kubernetes.io/cluster/id=owned" "kubernetes:application=kube-ingress-aws-controller"
Error: Error parsing parameter '--tags': Expected: '=', received: '/' for input:
kubernetes.io/cluster/id=owned,kubernetes:application=kube-ingress-aws-controller

**Comment by szuecs** [comment]
Can you show the values of your shell variables. You can do this if you follow again the kops.md guide and do, after these errors:

    $ echo aws ec2 authorize-security-group-ingress --group-id $sgidnode --protocol all --port -1 --source-group $sgidingress

and:

    $ echo aws ec2 create-tags --resources $sgidingress --tags "kubernetes.io/cluster/id=owned" "kubernetes:application=kube-ingress-aws-controller"

**Comment by itselavia** [comment]
Hi @szuecs, thank you for your response. I resolved both my problems. 

1. By default, the security groups created by the 'aws ec2 create-security-group' command were getting created in the default VPC. Whereas the security groups created by kops during cluster creation were in a separate VPC. So while creating the security groups, I added the vpc id as follows:

aws ec2 create-security-group --description ingress.$KOPS_CLUSTER_NAME --group-name ingress.$KOPS_CLUSTER_NAME --vpc-id <VPC_ID_HERE>

2. The "aws ec2 create-tags" command doesn't like '/' characters. This '/' character was needed for the "kubernetes.io/cluster/id" key. So I instead used the JSON format to provide the tags:

aws ec2 create-tags --resources $sgidingress --tags '[{"Key": "kubernetes.io/cluster/id", "Value": "owned"}, {"Key": "kubernetes:application", "Value": "kube-ingress-aws-controller"}]'

**Comment by baez90** [comment]
It's already mentioned in the docs but to get the same experience with a single script without the need to lookup the VPC-ID the following snippet might be helpful:

```bash
VPC_ID=$(aws ec2 describe-security-groups --filters Name=group-name,Values=nodes.$KOPS_CLUSTER_NAME | jq '.["SecurityGroups"][0].VpcId' -r)
```

**Comment by szuecs** [comment]
Thanks @baez90 , I created a PR for your proposed change in the docs.
