### ISSUE TITLE
Error when discovering previous ALBs

### ISSUE THREAD

**Issue by Raffo** [zalando-incubator/kube-ingress-aws-controller#13]
In the current implementation, the discovery of previously available ALBs in only done based on the ARN: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/worker.go#L76 
In case we have a previous existing ALB with the same ARN, this would would be discovered and attached correctly, but the target group will be empty.

**Comment by lmineiro** [comment]
nice find
