### ISSUE TITLE
Shit has hit the fan: panic caused by: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by johnwards** [zalando-incubator/kube-ingress-aws-controller#137]
Not sure what to do with this error other than post the stacktrace in the hope it makes sense to someone, I'm assuming I've done something wrong.. I'm using tectonic 1.8 latest btw.

```
2018/03/07 23:06:58 Start polling sleep 30s
2018/03/07 23:07:28 Found 4 ingresses
2018/03/07 23:07:28 Found 0 stacks
2018/03/07 23:07:28 Found 1 auto scaling groups
2018/03/07 23:07:28 Found 1 single instances
2018/03/07 23:07:28 Found 6 EC2 instances
2018/03/07 23:07:28 shit has hit the fan: panic caused by: runtime error: invalid memory address or nil pointer dereference
 goroutine 73 [running]: 
 runtime/debug.Stack(0x4bcc5c, 0xc4200980f0, 0x2)
  /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
 runtime/debug.PrintStack()
  /usr/local/go/src/runtime/debug/stack.go:16 +0x22
 main.doWork.func1(0xc42069bc40, 0xc4201d7080)
  /go/src/github.com/zalando-incubator/kube-ingress-aws-controller/worker.go:166 +0xf0 
 panic(0xabe6c0, 0x1165e80)
  /usr/local/go/src/runtime/panic.go:505 +0x229 
 github.com/zalando-incubator/kube-ingress-aws-controller/aws.(*Stack).OwnerIngress(...)
  /go/src/github.com/zalando-incubator/kube-ingress-aws-controller/aws/cf.go:53 
 main.(*managedItem).AddIngress(0xc420304180, 0xc420469400, 0x3f, 0xc4201b4d20, 0x19, 0x0)
  /go/src/github.com/zalando-incubator/kube-ingress-aws-controller/worker.go:83 +0x180
 main.buildManagedModel(0xcb6280, 0xc420531940, 0x19, 0x1a3185c5000, 0xc4204ca880, 0x4, 0x4, 0x1191240, 0x0, 0x0, ...)
  /go/src/github.com/zalando-incubator/kube-ingress-aws-controller/worker.go:258 +0x373
 main.doWork(0xcb6280, 0xc420531940, 0x19, 0x1a3185c5000, 0xc420278000, 0xc420458c40, 0xc42056e120, 0x0, 0x0)
  /go/src/github.com/zalando-incubator/kube-ingress-aws-controller/worker.go:194 +0x5d1
 main.startPolling(0xc42035eba0, 0xcb6280, 0xc420531940, 0x19, 0x1a3185c5000, 0xc420278000, 0xc420458c40, 0x6fc23ac00)
  /go/src/github.com/zalando-incubator/kube-ingress-aws-controller/worker.go:155 +0x287
 created by main.main
  /go/src/github.com/zalando-incubator/kube-ingress-aws-controller/controller.go:185 +0xbf0
2018/03/07 23:07:28 Start polling sleep 30s
```

**Comment by szuecs** [comment]
@johnwards thanks for creating the issue.  If this happens, it's always a bug in this software.

**Comment by johnwards** [comment]
@szuecs I'm using latest on everything, I basically copy and pasted the quick start on the read me last night and changed my region to eu-west-1.

eg https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/ingress-controller.yaml and https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/skipper.yaml

I had to add tag-keys to my worker nodes for discovery `tag-key=k8s.io/role/node` by hand as they didn't exist, it erroring before I did that as well. Not sure if I should have done that, or included master too?

**Comment by szuecs** [comment]
@johnwards for skipper please use v0.9.152, I am currently on it to fix an issue we have there. I informed users in our googlegroup https://groups.google.com/forum/?pli=1#!topic/skipper-router/MOK9xBjs0OE

**Comment by szuecs** [comment]
I could reproduce your error.

**Comment by szuecs** [comment]
@johnwards please update to v0.6.5.

**Comment by johnwards** [comment]
@szuecs Thanks, that's fixed it.

**Comment by szuecs** [comment]
@johnwards we fixed the problem in skipper, you can use the latest released version.
We will roll out the new skipper version to production next week.
