### ISSUE TITLE
Unable to create stack when cluster ID starts with a number

### ISSUE THREAD

**Issue by orangain** [zalando-incubator/kube-ingress-aws-controller#144]
When a cluster ID starts with a number, a stack is not created after deploying kube-aws-ingress-controller. I see the following log (modified partially):

```
2018/03/30 04:49:36 createStack(["arn:aws:acm:ap-northeast-1:xxxxxxxx:certificate/5407598b-0f61-4135-9f3c-dcf11b82bea9"]) failed: ValidationError: 1 validation error detected: Value '123456-cluster-kubernetes-example-com-5de9323f-6be3-48c9-8535-042da7f69308' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*
status code: 400, request id: bf8c17e0-33d5-11e8-b466-0b211f6a36be
```

My cluster ID is something like: `123456-cluster.kubernetes.example.com`. I think that a name starting with a number is valid as a domain name and a cluster ID, but it is invalid as a stack name of CloudFormation.

Adding fixed prefix during [normalization](https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/v0.6.6/aws/naming.go#L27-L38) or making stack name configurable will be a solution.

Note: I've used kops to create kubernetes cluster and read the [kops's guide](https://github.com/kubernetes/kops/tree/master/addons/kube-ingress-aws-controller) to deploy kube-aws-ingress-controller.

**Comment by mikkeloscar** [comment]
Thanks for reporting this! I think we should just prefix the stack name with a valid character in case the cluster ID starts with a number.
