### ISSUE TITLE
issues with generating cloudformation

### ISSUE THREAD

**Issue by ryohang** [zalando-incubator/kube-ingress-aws-controller#147]
Hello Dear,

I was reading through the documentation https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/cloudformation.md. I am trying to figure out how one can generate cloudformation template from Go. Is there any specific documentation or steps?

**Comment by hjacobs** [comment]
Can you elaborate on what you want to do? Do you have problems with running `kube-ingress-aws-controller` or are you trying to generate CF from Go in general.

**Comment by ryohang** [comment]
Sure Jacob, thanks for the quick response. I am having issue of (creating)associating the ALB to ingress controller by following two Read me. https://github.com/zalando-incubator/kube-ingress-aws-controller/tree/master/deploy and https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/test-deployment.md (Base feature)

I tried a few hours yesterday and tonight. I can only get this far. 
![deployer_app-prod-02___home_rhang__bash_](https://user-images.githubusercontent.com/429620/38632369-866bf43a-3d8a-11e8-9a6c-55e2dcc147f6.png)

The security group was created correctly and the instance role was assigned with admin role.... So I thought perhaps there is some other setup in the cloudformation. I went ahead generating the CFT from Go program but no luck.

**Comment by hjacobs** [comment]
Can you check the status of Cloud Formation stacks in the AWS Console?

**Comment by ryohang** [comment]
I don't see any cloudformation having been launched there. What could go wrong? Is ingress controller suppose to launch cloudformation template?

**Comment by szuecs** [comment]
@ryohang Could you post log output of the controller, please? 
I guess we miss something in our documentation that lead to, that the controller can not find the right data in your deployment, such that it does not create the cloudformation stack.

**Comment by szuecs** [comment]
To clean this up I will close this issue. Please feel free to reopen it.
