### ISSUE TITLE
Use k8s client for ingress resource listing 

### ISSUE THREAD

**Issue by ideahitme** [zalando-incubator/kube-ingress-aws-controller#15]
Current implementation makes use of the hardcoded structs for deserialisation and manual http calls to API server to list ingress resources. This might be difficult to maintain in the future
This should be changed to use the https://github.com/kubernetes/client-go. Examples can be found in https://github.com/zalando-incubator/mate/blob/master/producers/kubernetes/ingress.go#L45

**Comment by lmineiro** [comment]
This was an informed decision. The client libraries are massive and the "cost" you mentioned were considered reasonable.

**Comment by ideahitme** [comment]
it is only about 11Mb, but since it is an informed decision closing this issue
