### ISSUE TITLE
Takes ~20 minutes time to get response from newly created ingress...

### ISSUE THREAD

**Issue by lambertpan** [zalando-incubator/kube-ingress-aws-controller#150]
I tried kube-ingress-aws-controller. After I completed my cluster setup and everything, it almost took 20 minutes time to get response from ‘kubetest.mydomain.com’. What could be the reason? I deleted and created the ingress controller, I got the response immediately.

The delay response behavior is same for newly created cluster.

**Comment by mikkeloscar** [comment]
* How do you create the DNS entry?
* Could you check how long it takes going directly to the hostname of the ALB? Then we know if it's in this controller or somewhere else.

Thanks!

**Comment by lambertpan** [comment]
-  I have a domain name in route53. Once the ingress is set, I manually create the record and select ELB load balancer which is created by 'kube-ingress-aws-controller'.
- I am able to ping the services from nodes. [Or] I could reach them from kubectl proxy

**Comment by lambertpan** [comment]
Apologize, it looks like I made a mistake in security configuration. I added an extra rule
aws ec2 authorize-security-group-ingress --group-id $sgidingress --protocol all --port -1 --source-group $sgidnode - along with the other required rules.
After correcting this, it is starting with no time. I will check this again tomorrow. 
Thanks for your support.

**Comment by lambertpan** [comment]
I am sorry, again, today I am getting this issue. I am not sure it is because of security group (my previous ans is not valid).
@szuecs Answer to your question, I get the ALB in ingress status. So, do you mean it is question for route53?
Also, I need some clarification for my debugging - the external dns myname.mydomain->alias to ALB; from which or where the 'aws-ingress-controller' picks the traffic. Or how/which one picks the request from ALB?

**Comment by szuecs** [comment]
@lambertpan https://zalando.github.io/skipper/kubernetes/ingress-controller/#aws-deployment is I think the best picture I have to explain the full setup that you should use if you run the kube-ingress-aws-controller + skipper + external-dns stack.

My question was if you do a `kubectl get ing <your-ingres> -o json | jq '.status'` , do you see a value in the `hostname` field?

Example:

    {
     "loadBalancer": {
        "ingress": [
          {
            "hostname": "kube-ing-lb-crar2m1924sa-128331179.eu-west-1.elb.amazonaws.com"
          }
        ]
      }
    }

**Comment by lambertpan** [comment]
Yes. I can see the value in the hostname field. I figured out, it is due to external dns problem. ingress-controller is working great! thanks for that.
