### ISSUE TITLE
IAM Role for autoscaling group

### ISSUE THREAD

**Issue by lambertpan** [zalando-incubator/kube-ingress-aws-controller#151]
I followed the steps as mentioned at https://github.com/kubernetes/kops/tree/master/addons/kube-ingress-aws-controller, but I got an error “UpdateTargetGroupsAndAutoScalingGroups() failed to attach target groups to ASG: AccessDenied: User: arn:aws......is not authorized to perform”. 

I adjusted the IAM to “autoscaling:*”, then it worked.

**Comment by szuecs** [comment]
thanks for reporting back this issue!

**Comment by szuecs** [comment]
I opened a PR at https://github.com/kubernetes/kops/pull/5014

**Comment by szuecs** [comment]
documented in external repositories as well
