### ISSUE TITLE
Permissions issue Kubernetes 1.9+

### ISSUE THREAD

**Issue by oliver-whiteman** [zalando-incubator/kube-ingress-aws-controller#152]
Had everything working fine on Kubernetes 1.8 but now on 1.9 and I think I am hitting a permissions issue but not sure where. All skipper-ingress logs are showing:

[APP]time="2018-04-17T16:06:55Z" level=error msg="convertPathRule: Failed to get service default, server, 8026"
[APP]time="2018-04-17T16:06:55Z" level=error msg="failed to load all: error while getting service: request failed, status: 403, 403 Forbidden"
[APP]time="2018-04-17T16:06:55Z" level=error msg="error while receiveing initial data;error while getting service: request failed, status: 403, 403 Forbidden"

Any pointers appreciated

**Comment by volkertb** [comment]
As coincidence would have it, I ran into the same issue just now. Running with a Kubernetes 1.9.3 cluster installed through kops. In addition to skipper-ingress, the kube-ingress-aws-controller pod also failed to start with the error "unable to find instance "xxxxxxxxxx": no reservations or instances in the running state". Is that as a result of the errors in the skipper-ingress pods? Are you getting errors there too, @oliver-whiteman ?

**Comment by oliver-whiteman** [comment]
I'm running 1.9.3 on kops as well for reference

I was getting some issues on the kube-ingress-aws-controller around permissions for ingresses but the error messages meant I was able to create the correct clusterroles to fix it. With skipper-ingress I dont have enough info

Not seen the error you have there

**Comment by volkertb** [comment]
Thanks for checking. I found some potentially related information here: https://groups.google.com/forum/#!topic/skipper-router/v5ABRuXwDE4

**Comment by oliver-whiteman** [comment]
OK, managed to get it working by checking the api logs for the permissions required
For some reason the kube-system:default user didnt have permissions to get/list services, most be very locked down in new setup
Worth checking the logs for kube-apiserver for more info
