### ISSUE TITLE
Is it possible to configure ALB Idle timeout value?

### ISSUE THREAD

**Issue by shane-containership** [zalando-incubator/kube-ingress-aws-controller#155]
Is it possible to set the 'Idle timeout' value on ALBs created by the ingress controller? The documentation mentions being able to customize Cloudformation options using the [built-in template](https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/aws/ingress-cf-template.yaml). However, this file no longer exists.

I see that there is an open issue regarding the outdated documentation: #148 . Can you please let me know if it's currently possible to automatically set the 'Idle timeout' value? 

As a work-around, I used the AWS CLI to update the `idle_timeout.timeout_seconds` attribute on the ALB, after it has been created by the ingress controller. This works, but is less than ideal.

**Comment by szuecs** [comment]
@shane-containership right now it's not possible, but if this is a feature request we can build as flag to the ingress controller. :)

Does it makes sense to set this to the same value for all stack or should this be configurable as ingress annotation?
What kind of use case do you have for this feature?

**Comment by shane-containership** [comment]
Thanks for looking into this! 

For our use case, we currently only have a single stack/ALB for each cluster. So a flag passed to the Ingress Controller would be sufficient. 

However, I see value in allowing this to be specified as an annotation, at the ingress level. I'm just not sure how that would work for users like us, with a single aggregated ALB. If two separate ingresses had conflicting idle timeout values, I'm not sure what the expected behavior should be. I'm not very familiar with using this ingress controller with multiple stacks/ALBs, so I would appreciate feedback from users that are. 

As far as the specific AWS feature that you posted, I believe that one is for 'Classic' load balancers. ALBs are 'ELB v2' type resources, so the [Connection Idle Timeout](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout) would apply here. Here is an [example](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#w2ab2c21c10d635c14) of how to set that using Cloudformation. The `idle_timeout.timeout_seconds` attribute key in that example, matches the attribute flag that I passed to the CLI in my work-around.

**Comment by szuecs** [comment]
@shane-containership Do you want to test it?
Docker image is available at:

    registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.6.8-2-gee85e54

**Comment by shane-containership** [comment]
Thanks. I tried this out, and set the flag to `--idle-connection-timeout=20m1s`. Prior to this update, the timeout value was set to 1200 seconds (20 minutes). This was previously set manually using the AWS CLI. After adding the flag, there was no change to the ALB's timeout value. 

Is this only intended to set the initial timeout value when the ALB is created? Or should it update existing ALBs if they do not match the current flag's value?

**Comment by szuecs** [comment]
@shane-containership It will also do change on update, but you have to trigger an update event. For example create a new ACM certificate that will be picked up by the controller (and maybe an ingress referencing it).

**Comment by szuecs** [comment]
This task was done and a follow up issue #157 was created to trigger update all old stacks using a version field.

**Comment by szuecs** [comment]
version was released with v0.6.9
