### ISSUE TITLE
trigger update all old stacks

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/kube-ingress-aws-controller#157]
Right now there is no easy way to trigger updates for example (https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/155) on global configuration changes.
This would make it easily possible to force an update of all CF stacks with deleting the ingress controller pod and get everything updated.

**Comment by mikkeloscar** [comment]
Alternatively we could add a "version" to the stacks e.g. an incremental counter which is incremented whenever we make changes to the stack configuration. And the controller would only update all stacks with a mismatching version number.

**Comment by szuecs** [comment]
Let's do the versioning if it's simple enough to implement.

**Comment by jhohertz** [comment]
Was just browsing the open issues, wanted to share some thoughts on this one. I've noticed that outside of the cert list changing, there isn't really any other test for if the CF template is out of sync with the current configuration. (I've actually taken to provisioning and de-provisioning a dummy ingress to force it to sync up sometimes)

This is where the evaluation for "do we need to update?" happens:

https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/worker.go#L49-L51

If there were some method in the cf/cf_template code with it's own inSync() method, that could be added to the test above, and I *think* largely get the effect you want?

I might explore this more later, but was wondering if anyone had thoughts on this approach?

**Comment by humayunjamal** [comment]
@szuecs how can I trigger an update to the CF stack now ? I have added/enabled S3 logging for ALBs created (btw there is no documentation regarding this flag I had to browse the issues to dig this one out) 
where can I find documentation regarding the `version` flag ?

**Comment by szuecs** [comment]
@humayunjamal all of this "trigger an update to the CF" exist in theory and is not implemented, yet.
I am happy to review PRs also adding documentation for the S3 logging would be valuable.

You can possibly workaround the problem if you create a new cert and and ingress that "needs" this cert, which would trigger a CF update.

**Comment by humayunjamal** [comment]
@szuecs thanks will do that shortly

**Comment by szuecs** [comment]
A controller restart triggers now an update of all CF stacks.
