### ISSUE TITLE
Controller deletes other target groups from autoscaling group

### ISSUE THREAD

**Issue by ese** [zalando-incubator/kube-ingress-aws-controller#165]
Controller delete target groups from autoscaling group which are not managed by itself. This avoid have other stuff working with target groups managed by other components.

How to reproduce:
  * Create a target group
  * Add target group to the nodes autoscaling group

What happens:
  * kiac delete the target group from the autoscaling groups

What expect:
  * kiac maintain and don't delete stuff which is not managed by itself
  * kiac delete garbage target group looking for a label to know that was self-managed

**Comment by 56quarters** [comment]
I'm running into the same issue when attempting to run two instances of the controller, one for internal traffic and one for public internet traffic. The controllers each constantly attach their own target groups to the ASGs and remove the target group of the other controller.

**Comment by szuecs** [comment]
Thanks for testing and reporting the issue!
