### ISSUE TITLE
Tag filtering for subnets is apparently not working right?

### ISSUE THREAD

**Issue by jhohertz** [zalando-incubator/kube-ingress-aws-controller#167]
Sorry submitted this before I put a description in...

We are seeing the controller select subnets seemingly at random... where tags do not match the filter, causing cross-contamination between clusters, and in some cases selecting subnets not even tagged for k8s at all.

Just starting to gather details on this now.

**Comment by hjacobs** [comment]
Thanks for reporting, please let us know more context and details.

**Comment by jhohertz** [comment]
So I don't have much in the way of debug output that would be useful, as not much is emitted but I get on startup:

`2018/06/01 19:40:49     EC2 filters: tag:kubernetes.io/cluster/k8s.mydomain.net=owned tag-key=k8s.io/role/node`

The cluster tag on the proper subnets matches the log. The role tag confuses me a bit, as I have them tagged with k8s.io/role/elb and k8s.io/role/internal-elb for exterior and interior subnets respectively.

Despite the cluster only spanning 3 AZs, we see 4 interior and exterior subnets selected. Only one of these is the correct subnet, 2 are subnets for another k8s cluster, and a fourth subnet that has no k8s tags on it whatsoever.

Unless something jumps out at your I will start peppering debug log messages into a forked build for testing to get more details of where the logic is going wrong.

**Comment by szuecs** [comment]
@jhohertz can you post the first 10-15 log lines please?
We had a similar behavior when we started to use dynamic NAT networks created by github.com/szuecs/kube-static-egress-controller

**Comment by jhohertz** [comment]
Here is what's seen on startup:

````
2018/06/04 12:39:55 starting /bin/kube-ingress-aws-controller
2018/06/04 12:40:05 controller manifest:
2018/06/04 12:40:05     kubernetes API server: 
2018/06/04 12:40:05     Cluster ID: k8s.mydomain.net
2018/06/04 12:40:05     vpc id: vpc-597ca83c
2018/06/04 12:40:05     instance id: i-0655c746f8df6de30
2018/06/04 12:40:05     security group id: sg-09eba2974ed5c68e6
2018/06/04 12:40:05     internal subnet ids: [subnet-03c9dbbec0a63424c subnet-02fd59cc640f49d21 subnet-02af5bb6adac836fd subnet-60b87104]
2018/06/04 12:40:05     public subnet ids: [subnet-05806f73138e4fced subnet-60b87104 subnet-05726d1ddfc2cfa0f subnet-0658dca9929f7f099]
2018/06/04 12:40:05     EC2 filters: tag:kubernetes.io/cluster/k8s.mydomain.net=owned tag-key=k8s.io/role/node
2018/06/04 12:40:05     Cetificates Per ALB (SNI: true): 25
2018/06/04 12:40:05     Ingress class filters: skipper
2018/06/04 12:40:05 Start polling sleep 30s
```

**Comment by jhohertz** [comment]
So I have been into the code a bit @szuecs, and I think I see what's going on.

I can't see anywhere that the subnets get filtered on tag key `kubernetes.io/cluster/<cluster_name>` while it's doing the lookup. For the case of "using other cluster's subnets", it *is* checking on the role tag key, but the lexical order of the subnet ID is what's resulting in using the other cluster.

For the subnet-in-AZ-our-cluster-is-not being included, this is simply because it's seeking to fill in as many AZs as possible, and without the cluster tag filter, it makes it into the list.

So is this intended behaviour to not require tagging on the subnets for cluster, and to only use the role tag as a suggestion/preference? My inclination is to make the logic more strict about this, but worry about existing users relying on the present behaviour.

Perhaps I could wrap the more strict behaviour into a `--strict-subnet-tags` parameter?

**Comment by mikkeloscar** [comment]
> I can't see anywhere that the subnets get filtered on tag key kubernetes.io/cluster/<cluster_name> while it's doing the lookup.

This looks like a bug to me. We share subnets for our clusters so it was never an issue. But we should have support for limiting the subnets to those with a certain cluster ID if specified.

Note, this filter is about finding nodes:

```
2018/06/01 19:40:49 EC2 filters: tag:kubernetes.io/cluster/k8s.mydomain.net=owned tag-key=k8s.io/role/node
```

So it should not be confused with the logic for finding subnets, although the logic should ideally be similar.

**Comment by szuecs** [comment]
@mikkeloscar I think we saw this issue already with some users that use NAT subnets. 
I agree this is a bug and we should prefer tagged subnets in case we find networks with a tag.
Any reason not to do it like I suggest?

**Comment by jhohertz** [comment]
Please have a look at PR #169 which corrects the issue for me. Note: I haven't yet wrapped the change with any kind of flag to influence the behaviour.
