### ISSUE TITLE
When multiple ALBs, not attaching certificates on new ones

### ISSUE THREAD

**Issue by jchanam** [zalando-incubator/kube-ingress-aws-controller#175]
Hi,

We're facing an issue when more than 25 certificates are needed.

When the limit (done by AWS) is reached, a new ALB is created (this is done correctly). The problem is that when a new certificate has to be added to the second ALB and update the ingress status, this is not happening.

On new domains, the ingress status is set to the first ALB, but it should be to the second one (after attaching the certificate).

I don't know exactly where this happens on the code. I'll try to search and point it here.

Thanks.
KR.

**Comment by mikkeloscar** [comment]
Thanks for the bug report!

**Comment by ese** [comment]
some kind of black magic is happening here which lead to try to attach more certificates to one ALB than 25 limit
https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/14fb0703ba0e187e7bb837bf414d36f35f3a523f/worker.go#L112-L122

even fixing this you will face this #176

**Comment by jchanam** [comment]
Also, I've seen that when having more certificates, it does a cloudformation template with more certificates on it, causing a failure.

Could it be there's a bug on the code that @ese is pointing out?

I think that this `!ok` should be just `ok`, so the TTL is only changed if it exists and it won't add a new element on the map.

https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/14fb0703ba0e187e7bb837bf414d36f35f3a523f/worker.go#L113

So that line should be:
```
if _, ok := certificates[arn]; ok {
```

**Comment by jchanam** [comment]
Hi @szuecs,

What I can see on that piece of code
https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/14fb0703ba0e187e7bb837bf414d36f35f3a523f/worker.go#L106-L123
is the following:

* The managed item contains a list of ingresses (with a maximum defined of 25 by default) and also one stack (this is the CloudFormation stack with the certificates attached to it).
* What it creates, is a map with the ARN of a certificate and its TTL
* This list is generated by all the valid certificate ARN from the ingresses.

What I think, is that the Certificates attached to an stack don't have to be the same that are valid for the ingresses, so, when adding the TTL, it could cause that the list of ingresses does not have one of the certificates to be attached.

Exactly here: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/14fb0703ba0e187e7bb837bf414d36f35f3a523f/worker.go#L113

What it's going to do is that, if the list of certificates created from the ingresses does not have a certificate already attached to the Stack, it's going to be added to the list, causing that list to grow more than the limit stablished. As far as I know, this is because `item.ingresses` and `item.stack.CertificateARNs()` does not have to be necessarily the same (because of ordering).

Have I interpreted the code correctly? With this explanation said, can it make sense to change that `!ok` to `ok`, so the list is not increased?

**Comment by szuecs** [comment]
The proposed change would add multiple certificates with the same ARN (same cert) to the list, this would trigger the bug earlier I would expect. If you have 26 ingress and 2 certificates, one a wildcard covering 25 ingress and the other covers the 26th, than it could lead to 2 alb creations that might fail because you probably can’t attach a certificate twice.

**Comment by jchanam** [comment]
Hi!

As certificates is a `map[string]time.Time`, I think it'll only update the TTL, but will no increase the length of the map (as the `ok` is checked, in my proposal).

I think that what you are saying is what is happening now, because it'll only add an element if it does not exist.

If this is not the problem, what could cause it? Maybe I'm not understanding correctly the code because is a little bit complex, any help from @szuecs @mikkeloscar will be highly appreciated.

**Comment by mikkeloscar** [comment]
@jchanam I'm sorry I haven't had time to look at this yet. Will try to find some time one of the next days..

**Comment by szuecs** [comment]
@jchanam Can you try if registry.opensource.zalan.do/teapot/kube-ingress-aws-controller-test:pr-184-5 solves the issue for you?

**Comment by jchanam** [comment]
Hi @szuecs!

As @ese has pointed out on the PR, it's not fixing the issue.

It's still trying to create an ALB with more than the allowed certificates. As I told you before, I think it's because it's attaching every certificate available due to the extension of the map here:
https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/14fb0703ba0e187e7bb837bf414d36f35f3a523f/worker.go#L113

**Comment by szuecs** [comment]
@jchanam thanks for the reply

**Comment by jchanam** [comment]
If there's anything from me that could help solving the issue, I'll be super happy to try!

**Comment by szuecs** [comment]
Please reopen if you see a problem with the new version, that we will release in some minutes
