### ISSUE TITLE
Target group port 9999

### ISSUE THREAD

**Issue by JimtotheB** [zalando-incubator/kube-ingress-aws-controller#180]
Where is it set, and how can I change it?

Skipper seems great and all, and I'm sure Ill probably end up using it,  I'm somewhat new to Kubernetes and porting over a fairly large deployment. Dealing with Kube2iam, RBAC, kube-ingress, among others, I was hoping to just have a target group pointing at nginx or something until I could figure out what was going on before moving to the next step.

**Comment by szuecs** [comment]
You can also try without nginx or skipper and use a kubernetes service nodeport. You might need to change the target port to the range that works for the nodeport type.

If you want to understand the ingress setup better, I tried to explain it at https://opensource.zalando.com/skipper/kubernetes/ingress-controller/. If you have any questions please file an issue and I try to make the docs better.

**Comment by lmineiro** [comment]
@JimtotheB I think this default can be customized. It's part of the CF definition. Check the CF docs https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/cloudformation.md#customization and see if that helps

**Comment by mikkeloscar** [comment]
Currently the target port is the same as the healthcheck port. You can change it using the flag: `-health-check-port`. There's a PR to split this up so it doesn't have to be the same port for health and target (https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/161).

**Comment by JimtotheB** [comment]
@szuecs @lmineiro @mikkeloscar Thanks a lot for the quick reply. Unfortunately I'm not much further along than I was the other day. I was really just looking for something to manage an ALB and certs then send the traffic into k8 for me to do with what I wanted, I think this lib comes with some assumptions that don't fit my use case. I'm looking for a little less magic than this + skipper provide.

My original question was answered perfectly, so Ill close this.
