### ISSUE TITLE
TCP connection and expose ports except 80 and 443

### ISSUE THREAD

**Issue by Alados** [zalando-incubator/kube-ingress-aws-controller#181]
Could you help me, I tried create postgresql server. But for expose 5432 port I had to create LoadBalancer service. I can't expose this port in ingress. Also ingress by default not support TCP connection, and I can't connect to my database.

Is there a way to solve this problem?

**Comment by mikkeloscar** [comment]
Kubernetes ingress is only designed to handle L7 (HTTP) traffic so it's not the right tool for what you are doing.

A service of type `LoadBalancer` is the way I would suggest to do it.
