### ISSUE TITLE
Ipv6 support

### ISSUE THREAD

**Issue by zioalex** [zalando-incubator/kube-ingress-aws-controller#182]
I was trying to setup an IPv6 endpoint with the created ALB but I do not find any reference to it.

Is it supported or do you have any plan to support it?

**Comment by zioalex** [comment]
Yep @szuecs  it is exactly what I meant. And it is already supported by AWS in VPC and ALB ( https://aws.amazon.com/blogs/aws/aws-ipv6-update-global-support-spanning-15-regions-multiple-aws-services/ ) . I tested and IPv6 is ok.
The opt-in annotation would be great. it should also have the option "both" to configure ipv4 and ipv6.

**Comment by mikkeloscar** [comment]
@szuecs By annotation do you mean per ingress?

This sounds more like a global configuration that should be set by a flag, since the HTTP routing happens in a router like skipper, we couldn't determine, at the ALB level, if we should send ipv4 or ipv6 traffic to the cluster based on hostname.

**Comment by szuecs** [comment]
@zioalex I would prefer dualstack instead of both, but yes you are right makes sense. 

@mikkeloscar the problem is that we configure ALB to have only ipv4 addresses. I think we could add ipv6 and or dualstack.
Global flag will configure default and ingress annotation can overwrite it, which would have to create another alb. Skipper should not have a problem with kubernetes ipv6 endpoints.
The backend calls from alb point of view is for example skipper, which could also have an ipv6 address. Maybe @zioalex can clarify which is the most important part, because this could be 2 different pull requests.

**Comment by zioalex** [comment]
@szuecs Yep maybe duakstack is better, pointing us directly to the AWS terminology.
I think that the most important point here is to have the ALB configured also with ipv6. 
Having Skipper ready is desirable but not required at this point because you can have an ALB configured independently by it. At the DNS level ipv6 will be supported with this [#576](https://github.com/kubernetes-incubator/external-dns/pull/576)

**Comment by szuecs** [comment]
I tried this, but did not work (have to check how this can be put into CF:

```
diff --git a/aws/cf.go b/aws/cf.go
index 9175a0b..1e94308 100644
--- a/aws/cf.go
+++ b/aws/cf.go
@@ -145,6 +145,17 @@ func createStack(svc cloudformationiface.CloudFormationAPI, spec *stackSpec) (st
                        cfParam(parameterLoadBalancerSubnetsParameter, strings.Join(spec.subnets, ",")),
                        cfParam(parameterTargetGroupVPCIDParameter, spec.vpcID),
                        cfParam(parameterTargetTargetPortParameter, fmt.Sprintf("%d", spec.targetPort)),
+                       //TODO(fix):
+                       // 2018/07/25 09:31:18 creating stack for certificates ["arn:aws:acm:eu-central-1:170858875137:certificate/67609df3-5797-4
+                       // 0f7-ae7d-d3735c8315bd" ..
+                       //       / ingress map["arn:aws:acm:eu-central-
+                       // .."])failed: ValidationError: Parameters: [IpAddressType] do not exist in the template
+                       //         status code: 400, request id: 7c26aa6c-8fed-11e8-bbc4-d1bd7f568fc6
+                       // 2018/07/25 09:31:18 creating stack for certificates ["arn:aws:acm:eu-central-1:170858875137:certificate/624e0094-2561-45c4-98bf-0d0c7d20e84f" "arn:aws:acm:eu-central-1:170858875137:certificate/4861ae55-5e3c-4ae8-a9c3-b3f8f2c70b2f" "arn:aws:acm:eu-central-1:170858875137:certificate/75c34966-5df3-46c9-9dc2-cb2c750b5711"] / ingress map["arn:aws:acm:eu-central-1:170858875137:certificate/75c34966-5df3-46c9-9dc2-cb2c750b5711":["default/sszuecs-demo-kiac-7"] "arn:aws:acm:eu-central-1:170858875137:certificate/624e0094-2561-45c4-98bf-0d0c7d20e84f":["default/sszuecs-demo-kiac-8"] "arn:aws:acm:eu-central-1:170858875137:certificate/4861ae55-5e3c-4ae8-a9c3-b3f8f2c70b2f":["default/sszuecs-demo-kiac-9"]]
+                       // 2018/07/25 09:31:18 createStack(["arn:aws:acm:eu-central-1:170858875137:certificate/624e0094-2561-45c4-98bf-0d0c7d20e84f" "arn:aws:acm:eu-central-1:170858875137:certificate/4861ae55-5e3c-4ae8-a9c3-b3f8f2c70b2f" "arn:aws:acm:eu-central-1:170858875137:certificate/75c34966-5df3-46c9-9dc2-cb2c750b5711"]) failed: ValidationError: Parameters: [IpAddressType] do not exist in the template
+                       //         status code: 400, request id: 7c31cdfe-8fed-11e8-bbc4-d1bd7f568fc6
+
+                       cfParam("IpAddressType", "dualstack"),
                },
```

**Comment by zioalex** [comment]
It should be correct looking here
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html
:

{
  "Type" : "AWS::ElasticLoadBalancingV2::LoadBalancer",
  "Properties" : {
    "IpAddressType
<https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-ipaddresstype>"
: *String*,
    "LoadBalancerAttributes
<https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-loadbalancerattributes>"
: [ LoadBalancerAttributes
<https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-loadbalancerattributes.html>,
... ],
    "Name <https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-name>"
: *String*,
    "Scheme <https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-scheme>"
: *String*,
    "SecurityGroups
<https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-securitygroups>"
: [ *String, ...* ],
    "SubnetMappings
<https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-subnetmappings>"
: [ SubnetMapping
<https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-subnetmapping.html>,
... ],
    "Subnets <https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-subnets>"
: [ *String, ...* ],
    "Tags <https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-tags>"
: [ *Resource Tag, ...* ],
    "Type <https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-type>"
: *String*
  }
}

IpAddressType

[Application Load Balancers] The type of IP addresses that are used by the
load balancer's subnets, such as ipv4 (for IPv4 addresses) or dualstack
(for IPv4 and IPv6 addresses). For valid values, see the IpAddressType
parameter for the CreateLoadBalancer
<http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateLoadBalancer.html>
action in the *Elastic Load Balancing API Reference version 2015-12-01*.
The default value is ipv4.

*Required*: No

*Type*: String

*Update requires*: No interruption
<https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt>

Note

If Scheme is internal, then IpAddressType must be ipv4.

**Comment by szuecs** [comment]
@zioalex could you try registry.opensource.zalan.do/teapot/kube-ingress-aws-controller-test:pr-209-1 in a test cluster with `-ip-addr-type=dualstack`?

It only works with the flag, no overwrite by ingress, but this was a thing I could do fast.

**Comment by szuecs** [comment]
A new release was created.

Published docker container `registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.7.4`
