### ISSUE TITLE
Stack creation failed by ingress controller

### ISSUE THREAD

**Issue by leidixujian** [zalando-incubator/kube-ingress-aws-controller#188]
Hello, i am testing the ingress aws controller. When I launched the ingress controller and log the pod. It failed to create stack in cloudformation. 

I've checked in aws console. The creation of LB was failed due to "At least two subnets in two different Availability Zones must be specified (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: ValidationError).  And the ingress repeats to create the stack

<img width="1272" alt="screen shot 2018-07-09 at 2 48 56 pm" src="https://user-images.githubusercontent.com/36231655/42451348-3d295338-8387-11e8-982d-b056413a2b9c.png">

Bellow is the log from the pod of ingress controller : 
```
2018/07/09 12:31:34 	Certificates per ALB: 24 (SNI: true)
2018/07/09 12:31:34 	Ingress class filters:
2018/07/09 12:31:34 Start polling sleep 30s
2018/07/09 12:32:04 Found 2 ingress(es)
2018/07/09 12:32:04 Found 0 stack(s)
2018/07/09 12:32:04 Found 1 auto scaling group(s)
2018/07/09 12:32:04 Found 0 single instance(s)
2018/07/09 12:32:04 Found 3 EC2 instance(s)
2018/07/09 12:32:04 Have 1 model(s)
2018/07/09 12:32:04 creating stack for certificates ["arn:aws:acm:eu-west-1:xxxxxxxx:certificate/xxxxxxx"] / ingress map["arn:aws:acm:eu-west-1:xxxxxx:certificate/xxxxxxxx":["default/demo-feature-toggle" "default/demo-v1"]]
2018/07/09 12:32:04 stack "arn:aws:cloudformation:eu-west-1:xxxxxx:stack/kube-ingress-aws-controller-xxxxx" for certificates ["arn:aws:acm:eu-west-1:xxxxxx:certificate/xxxx"] created
```

**Comment by mikkeloscar** [comment]
@leidixujian See here for how subnets are discovered and make sure you have them setup like this in your VPC: https://github.com/zalando-incubator/kube-ingress-aws-controller#discovery

**Comment by leidixujian** [comment]
@mikkeloscar Thanks for the response. I reseted my VPC to 3 subnets and the ingress controller runs.
