### ISSUE TITLE
Controlling ASGs used for target group selection.

### ISSUE THREAD

**Issue by jhohertz** [zalando-incubator/kube-ingress-aws-controller#195]
I have so far failed to track this down, and thought I might just ask...

What is the mechanism by which the controller will look for instances to add to the target group, and how can we control that?

Scenario I am seeing is that I have a dedicated ASG for a certain purpose which, via taints, is *not* running the skipper that the controller forwards to. However these appear in the target group regardless. I assume there is a tag involved on the ASG, but thus far can't determine what that is.

Can you point me in the right direction?

**Comment by mikkeloscar** [comment]
See `CUSTOM_FILTERS` here: https://github.com/zalando-incubator/kube-ingress-aws-controller#how-it-works

**Comment by jhohertz** [comment]
Ahhhh, I was looking through the code for flags vs. env vars. :)

This totally addresses what I needed, thank you for the pointer.
