### ISSUE TITLE
Access logs configuration

### ISSUE THREAD

**Issue by sgmiller** [zalando-incubator/kube-ingress-aws-controller#201]
It'd be nice to be able to configure the Access Logs for the ALBs created.  Even better would be to have different logging per host, but that's impossible without a separate ALB per domain.

**Comment by szuecs** [comment]
If you would like to add a PR would be fine!

**Comment by szuecs** [comment]
closed by https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/222
