### ISSUE TITLE
Controller doesn't delete stale load balancers

### ISSUE THREAD

**Issue by timurkhafizov** [zalando-incubator/kube-ingress-aws-controller#203]
Recently I've installed `kube-ingress-aws-controller`, configured it to work with Traefik (because it was a router we used before) and tested. Seems to be doing job very good!

Unfortunately, I've faced an issue where Controller doesn't remove ALB even if there are no matching Ingress.
In Readme I can see that Controller is supposed to remove ALB: https://github.com/zalando-incubator/kube-ingress-aws-controller#deleting-load-balancers:

> When the controller detects that a managed load balancer for the current cluster doesn't have a matching ingress resource anymore, it deletes all the previously created resources.

Meantime I can't see it happening.

Here is how I tested it.

- Enable Ingress:
```
2018/08/17 14:35:55 Found 1 ingress(es)
2018/08/17 14:35:55 Found 1 stack(s)
2018/08/17 14:35:56 Found 1 auto scaling group(s)
2018/08/17 14:35:56 Found 0 single instance(s)
2018/08/17 14:35:56 Found 3 EC2 instance(s)
2018/08/17 14:35:56 Found 10 certificate(s)
2018/08/17 14:35:56 Have 1 model(s)
2018/08/17 14:35:56 updating "internal" stack for 1 certificates / 1 ingresses
2018/08/17 14:35:56 stack "arn:aws:cloudformation:eu-west-1:123456789:stack/kube-ingress-aws-controller-id/arn" for certificate map["arn:aws:acm:eu-west-1:123456789:certificate/cert-arn":"0001-01-01 00:00:00 +0000 UTC"] updated
2018/08/17 14:35:56 updated ingress kube-system/traefik with DNS name "internal-kube-ing-lb-id.eu-west-1.elb.amazonaws.com"
```

- Confirming all good:
```
2018/08/17 14:37:58 Found 1 ingress(es)
2018/08/17 14:37:58 Found 1 stack(s)
2018/08/17 14:37:59 Found 1 auto scaling group(s)
2018/08/17 14:37:59 Found 0 single instance(s)
2018/08/17 14:37:59 Found 3 EC2 instance(s)
2018/08/17 14:37:59 Found 10 certificate(s)
2018/08/17 14:37:59 Have 1 model(s)
2018/08/17 14:37:59 Ingress update not needed kube-system/traefik with DNS name "internal-kube-ing-lb-id.eu-west-1.elb.amazonaws.com"
```

- Disable Ingress:
```
2018/08/17 14:40:01 Found 0 ingress(es)
2018/08/17 14:40:01 Found 1 stack(s)
2018/08/17 14:40:02 Found 1 auto scaling group(s)
2018/08/17 14:40:02 Found 0 single instance(s)
2018/08/17 14:40:02 Found 3 EC2 instance(s)
2018/08/17 14:40:02 Found 10 certificate(s)
2018/08/17 14:40:02 Have 1 model(s)
2018/08/17 14:40:02 updating "internal" stack for 1 certificates / 1 ingresses
2018/08/17 14:40:02 stack "arn:aws:cloudformation:eu-west-1:123456789:stack/kube-ingress-aws-controller-id/arn" for certificate map["arn:aws:acm:eu-west-1:123456789:certificate/cert-arn":"2018-08-17 15:10:02.389316669 +0000 UTC"] updated
```

- Here I would expect Controller to remove ALB since there are no Ingress, but it continues polling and doesn't remove ALB:
```
2018/08/17 14:41:33 Found 0 ingress(es)
2018/08/17 14:41:33 Found 1 stack(s)
2018/08/17 14:41:34 Found 1 auto scaling group(s)
2018/08/17 14:41:34 Found 0 single instance(s)
2018/08/17 14:41:34 Found 3 EC2 instance(s)
2018/08/17 14:41:34 Found 10 certificate(s)
2018/08/17 14:41:34 Have 1 model(s)
```

Am I missing something? Are there any other conditions to make Controller removing ALB?

Thanks in advance!

**Comment by szuecs** [comment]
We only mark to delete and clean up later, because there could be open connections not already served.
You just have to wait a bit to get it cleaned up automatically

**Comment by timurkhafizov** [comment]
@szuecs thanks. How long should one for the cleanup?

**Comment by timurkhafizov** [comment]
Based on my tests it takes 30 minutes for orphaned stack to be deleted.
Thanks for the info!
