### ISSUE TITLE
Support for rewrite target

### ISSUE THREAD

**Issue by rverma-nikiai** [zalando-incubator/kube-ingress-aws-controller#204]
Can we target support for  `ingress.kubernetes.io/rewrite-target` as available in heptio / nginx ingress controllers.

**Comment by szuecs** [comment]
Sure! Do you like to  provide a PR?

**Comment by mdinuth** [comment]
Any update on this please?

**Comment by szuecs** [comment]
@mdinuth no, but feel free to create a PR. I am happy to review and merge it.

**Comment by mikkeloscar** [comment]
This functionality should be handled by the backing proxy IMO. For instance skipper used as ingress controller can do this with something like `modPath`: https://opensource.zalando.com/skipper/kubernetes/ingress-usage/#modify-path
