### ISSUE TITLE
Unable to create ALB automatically when I create new cluster with kops

### ISSUE THREAD

**Issue by wwyhy** [zalando-incubator/kube-ingress-aws-controller#210]
Hi,

I am created new k8s on AWS with kops, and I added the --cloud-labels, secruity group and grant these permissions. 

After cluster created, the ALB and target group cannot be created automatically, I checked the logs of container of kube-ingress-aws-controller. there is no error.

Could you please help on this? 

```
---------------------------
2018/09/05 07:23:52 Start polling sleep 30s
2018/09/05 07:24:22 Found 0 ingress(es)
**2018/09/05 07:24:22 Found 0 stack(s)**
2018/09/05 07:24:22 Found 1 auto scaling group(s)
2018/09/05 07:24:22 Found 0 single instance(s)
2018/09/05 07:24:22 Found 2 EC2 instance(s)
2018/09/05 07:24:22 Found 1 certificate(s)
2018/09/05 07:24:22 Have 0 model(s)
2018/09/05 07:24:22 Start polling sleep 30s
--------------------------------
```

**Comment by mikkeloscar** [comment]
Looks like you don't have any ingresses in your cluster.

**Comment by wwyhy** [comment]
Yes, but it should create the ALB first, then after create the ingress, it will route to the ALB.
Now the ALB could not be created and it is empty in CloudFormation.  

I tried to create one ingress, but it does not help. still cannot found the ALB in "ADDRESS" column.

**Comment by mikkeloscar** [comment]
You need to create an ingress resource in the cluster before the controller will create any ALBs.

The logs you showed lists 0 ingresses so it's the only problem I can see. Maybe you can post the logs when running it in the cluster with ingresses.

also the output of `kubectl get ingress -o yaml` would be helpful.

**Comment by szuecs** [comment]
@wwyhy the status field will be set from the controller, if the ALB is ready.

**Comment by wwyhy** [comment]
Solved.

Thank you, Indeed, we need create ingress first, then the ALB can be created automatically (after 5~10 minutes).
