### ISSUE TITLE
v0.8.0 not tagged in zalando's docker registry

### ISSUE THREAD

**Issue by kciredor** [zalando-incubator/kube-ingress-aws-controller#215]
docker: Error response from daemon: manifest for registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.8.0 not found.

Could you please tag it? It appears 'latest' is actually v0.8.0. Tnx!

**Comment by szuecs** [comment]
I retriggered the pipeline that creates the docker container, thanks for creating this issue!
It's now available.
