### ISSUE TITLE
ALB not created in a VPC with public and private subnets across AZs

### ISSUE THREAD

**Issue by tareks** [zalando-incubator/kube-ingress-aws-controller#217]
It appears that I've hit a bit of a strange situation where the cloud formation stack for an internet facing ALB fails and enters a creation/deletion loop as `LoadBalancerSubnetsParameter` appears to not get populated at creation time. Strangely enough, with the same  exact setup, creating an ingress with `zalando.org/aws-load-balancer-scheme: internal` will successfully create an internal load balancer without issues. I can also manually create the internet facing ALB without problem with the same networking configuration. I suspect I'm missing something or this may be a corner case that may not be currently handled?

Some details about the setup:
Using EKS:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Using Skipper on port 9999:
`registry.opensource.zalan.do/pathfinder/skipper:v0.10.5`

Using kube-ingress-aws-controller:
`registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:latest`

The underlying network configuration is as follows:
- 1 VPC
- 1 Internet Gateway
- 1 NAT Gateway
- 3 Public subnets, one in each AZ
- 3 Private subnets, one in each AZ (Worker instances live here)

It is possible to configure the ALB to back onto EC2 instances sitting on the private subnets following: https://aws.amazon.com/premiumsupport/knowledge-center/public-load-balancer-private-ec2/

Note that when the EC2 instances are located on public subnets instead of private subnets, there are no problems provisioning the internet facing ALB across the 3 AZs.

Any ideas why this could be happening? I tried tagging the public subnets with `kubernetes.io/role/elb` but it doesn't seem to be picking any of them up.

**Comment by grahamar** [comment]
@tareks I had the same issue when I was creating my EKS cluster in an existing VPC. Internal LB was fine, as you mentioned it is for you too, I'll focus on what I did for internet facing LB.

I had to manually tag each public subnet with both the following (replacing `{cluster_name}` with your cluster name):

```
kubernetes.io/cluster/{cluster_name}=shared
kubernetes.io/role/elb=true
```

In addition I also tagged the route tables, NAT gateways and Internet Gateways with the tag `kubernetes.io/role/elb=true`. After doing that I deleted the kube-ingress-aws-controller deployment and re-created it. It then picked up my public and private subnets correctly and the cloudformation stack completed successfully.

Hope that helps!

**Comment by tareks** [comment]
Cheers @grahamar, I'll give that a try. 

One observation is that I came in this morning and it looked like it magically fixed itself overnight! I have an ASG scheduled to scale down the worker nodes to 0 and then back up in the morning. It looked like the internet facing ALB got created without issues with the same setup i was struggling with yesterday. Perhaps the kube-ingress-aws-controller needed a redeploy/kick to pick up the tags? Without changing anything, I can now spin up internal and internet facing ALBs based on the ingress annotations.

For what its worth, the tags i have on the subnets (only) are as follows:

Internet Facing:
Name: `kubernetes.io/cluster/<clustername>` Value: ""
Name: `kubernetes.io/role/elb` Value: ""

Internal:
Name: `kubernetes.io/cluster/<clustername>` Value: ""
Name: `kubernetes.io/role/internal-elb` Value: ""

Guess we can close this for now unless some oddities appear. :)
