### ISSUE TITLE
Support "internal" Application Load Balancers

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kube-ingress-aws-controller#22]
Support an annotation to create an `internal` ALB instead of `internet-facing`. The annotation for the Kubernetes ELB integration is `service.beta.kubernetes.io/aws-load-balancer-internal`. See https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L78

**Comment by hjacobs** [comment]
This is low priority for me (it's not needed in our Zalando context), but we should support it for completeness and other users.

**Comment by mumoshu** [comment]
@hjacobs @jalonsoa Just get to see this issue. Can we close this as per #104 now?

**Comment by mikkeloscar** [comment]
@mumoshu yes, this is solved as per #104 and #115. Thanks for pointing it out :)
