### ISSUE TITLE
add ELB/NLB support - was: [Bug] Incorrect ALB response

### ISSUE THREAD

**Issue by so0k** [zalando-incubator/kube-ingress-aws-controller#229]
Ref: https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/199#issuecomment-443662102

We identified an issue with ALB sometimes sending the incorrect response, this issue is most likely not related to kube-ingress-aws-controller at all.

we tried fixing it by using `-max-certs-alb=1`, but we are using wildcard certificates, so this still caused an issue with `test-a.foo.com` and `test-b.foo.com` something returning the wrong response.

right now, we are testing by creating non-wildcard certificates

**Comment by so0k** [comment]
AWS ALB seems to drop query path sometimes, causing incorrect responses, switching the ALB for an ELB doesn't cause these issues (but cert handling is very different as we can only have 1 listener per cert) - effectively need 1 ELB per cert

**Comment by szuecs** [comment]
If alb is dropping the query, it’s probably an issue in aws and not in this project. I did not see this happening, but also did not tested it. 
For sure we have no option to configure this behavior and I would recommend creating an issue in your aws console or check the service behind the alb. Do you use skipper or traefik behind the alb?

**Comment by so0k** [comment]
@szuecs - correct this is merely a follow up from the previous discussion as you asked me to create a separate issue. Initially we assumed it was some issue with host based routing or SNI

but hitting the nodePorts directly and later switching over to ELBs solved this issue. I created the issue in case others hit the same problem. It doesn't matter if we use skipper or envoy for ingress routing.

kube-ingress-aws-controller has an important feature (`custom_filters` ) which allows us to target edge nodes only, I don't know of any other ingress controller that allows us to do that (if we use k8s svc of type LoadBalancer, they would hit nodePorts across all our cluster nodes, which we can not do based on an agreed upon architectural design). I've spent a few hours looking if it would be possible to replace the code creating the ALB with code creating an ELB ... but it is very different way of configuration. 

We are indeed also creating a ticket with AWS regarding this bug in ALB

**Comment by szuecs** [comment]
@so0k Thanks for the clarification.
Maybe we can really create an ELB or also NLB, but should it work on `ingress` objects or better `service type loadbalancer` objects?
We would need a fully different CF stack, but the data should be already available and if you like to create a PR, I am happy to review and test it.

**Comment by so0k** [comment]
We've been running with ELB's managed through Terraform (to only target subset of kube workers, similar to the `custom_filters` setting) and had WSS issues.

We're now testing with NLB's (which will require the usage of http://cert-manager.readthedocs.io/ instead of AWS Certificate Manager - sorry this takes long

**Comment by szuecs** [comment]
Since a while, you can use NLBs instead of ALBs. Ingress annotation:
`zalando.org/aws-load-balancer-type: nlb`
