### ISSUE TITLE
Consider allowing to configure ALB security group

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kube-ingress-aws-controller#23]
Idea: allow configuring the ALB security group via annotations:

* the optional `zalando.org/aws-load-balancer-security-group` annotation can select a different AWS Security Group by name
* the default AWS Security Group can be configured via a command line option

This allows using a default security group with IP restrictions and explicitly exposing the ALB by selecting an unrestricted security group.

**Comment by lmineiro** [comment]
Could we consider another, similar, annotation where a ruleset could be defined?
I'm thinking about those scenarios where a deployer user doesn't have the access level that allows him to create a security group to reference but also wants to customize the security rules for his load balancer.

**Comment by hjacobs** [comment]
@lmineiro I would try to keep it simple, specifying the full set of ingress rules is overkill (as annotation). My scenario does not necessarily require AWS rights, the security groups could pre-provisioned for known use cases (something like "restricted/company-internal" SG with IP restrictions and another one "public" for exposure).

**Comment by lmineiro** [comment]
Fair enough. Let's keep it simple

**Comment by joberdick** [comment]
@hjacobs any thoughts on specifying security group by a tag instead of SG name? We automatically generate clusters with supporting SG's. Our SG names are dynamic. We could easily tag them with consistent names such as "internet-public".

**Comment by szuecs** [comment]
@joberdick feel free to create a new issue for your use case. 
The question from my point of view is:
- How this should work for shared ALBs and the user point of view?
- Would you tag all ingress with the same SG-Tag annotation? 

If you can write down what you want and define a workflow how to use it, it would be simpler to think about the solution.
