### ISSUE TITLE
Using with EKS private subnet POD for ingress-controller not getting assigned right iptable

### ISSUE THREAD

**Issue by wickstargazer** [zalando-incubator/kube-ingress-aws-controller#234]
Hey guys,

I am running into trouble when using with EKS and in private subnet. The ingress-controller pod is not getting assigned the private ip on eth0.

This does not happen with skipper. Please help.

`Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         169.254.1.1     0.0.0.0         UG        0 0          0 eth0
169.254.1.1     0.0.0.0         255.255.255.255 UH        0 0          0 eth0`

thats all the ips i got. instead of a bunch more which starts with 172.31.0

**Comment by szuecs** [comment]
I don't know the VPC setup of EKS, but in general the controller needs **no** access to a specific interface. It only needs AWS credentials (for example kube2iam) and access to AWS API with the go AWS SDK. 
In my opinion the problem you try to investigate should be something else.

**Comment by mikkeloscar** [comment]
Closing this as the problem seem to be unrelated to the project. Please re-open if you have more information.
