### ISSUE TITLE
enhance WAF support to be per ingress

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/kube-ingress-aws-controller#238]
Basic WAF support was implemented in https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/237.
One drawback of this implementation that, it is only possible to set a fixed WAF ID for all ALBs created by the controller.
A better solution would be to be able to set this via ingress annotation, too. For example  `zalando.org/aws-load-balancer-waf-id: "foobar"`

If we implement this we need to force to create another ALB and merge all similar chosen WAF IDs to this one. We already have a similar annotation `zalando.org/aws-load-balancer-shared: "false"` to force a non shared ALB. I see 2 solutions for this:
1. Force a WAF ID which is != default WAF to have the same behavior as `zalando.org/aws-load-balancer-shared: "false"` (seems to me a simple solution to add)
2. A WAF ID which is != default WAF is able to find similar ingress to create a shared ALB to group by WAF ID.

I would prefer Option 2, because it would increase cost efficiency, because it would reduce the number of ALB instances.

**Comment by amila-ku** [comment]
@szuecs i will start to work on this.

**Comment by szuecs** [comment]
This was done by @amila-ku
