### ISSUE TITLE
Controller fails to cleanup old Target groups from empty Autoscaling groups.

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/kube-ingress-aws-controller#239]
Imagine the following scenario:

1. You have a cluster with two autoscaling groups **asg-a** and **asg-b**. Both ASGs have **1** instance running each.
2. You deploy an ingress resource, which triggers the controller to create an ALB and attach Target groups to the two ASGs.
3. **asg-b** is scaled down to **0** instances (for whatever reason, e.g. cluster autoscaling).
4. You delete your ingress resource and the controller decommissions the ALB and target groups.
5. The controller finds that one instance in **asg-a** and removes the "ghost" Target Group from the ASG. Because **asg-b** didn't have any instances running at this time, the controller doesn't detect that **asg-b** exists, and therefore **DOESN'T** remove the ghost target group.
6. At a later point the cluster tries to scale up **asg-b** but fails because of the ghost target group:
![image](https://user-images.githubusercontent.com/128566/51943245-4e6c1800-2419-11e9-855e-439a9767821a.png)
    ```
    Status Reason: One or more target groups not found. Validating load balancer configuration failed.
    ```
7. The cluster can no longer scale up **asg-b** until someone manually removes the ghost target group from the ASG via the AWS Console.

This bug happens because ASGs are discovered by looking at tags of running EC2 instances:

https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/c5fd0b24ae038b0dee973cfb19ae7c86e881dad6/aws/adapter.go#L622

Thus it will never discover ASGs with no instances running. We should fix this by having the controller list all the ASGs.

**Comment by szuecs** [comment]
It should be fixed by the linked PR #245
