### ISSUE TITLE
Automatically select the right SSL certificate ARN

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kube-ingress-aws-controller#24]
There is no reason why a human needs to manually find out the SSL cert ARN (e.g. with `aws acm list-certificates` on the command line). We can automatically select the right SSL certificate based on the Ingress `host`:

* Introduce a new annotation to force non-SSL (HTTP) (SSL should be the default so users should explicitly ask for non-SSL Ingress)
* Unless non-SSL is forced: go through the list of specified hostnames and find the right SSL certificate ARN for each of them 
* The logic can be similar to [what Senza does in the `get_ssl_cert` function](https://github.com/zalando-stups/senza/blob/master/senza/components/elastic_load_balancer.py#L28).
  * Prefer ACM over uploaded AWS IAM certificates
  * Consider wildcard and multi-domain certs
* Bail out if there are multiple hostnames defined but no single SSL certificate matches all of them (e.g. a user specified "foo.example.org" and "foo.example.com" and no such multi-domain cert exists on AWS)
* Manual selection of the SSL certificate should still be possible (this is also required for Ingress without any `host` rule, i.e. where we can't discover the cert automatically)

Example list of ACM certs where we need to automatically select the wildcard cert if Ingress specifies a hostname like `foo.teapot.example.org`:
```
aws acm list-certificates
{
    "CertificateSummaryList": [
        {
            "DomainName": "teapot.example.org",
            "CertificateArn": "arn:aws:acm:eu-central-1:123:certificate/44477102-1289-4ecc-8cf1-24a7ec4474e5"
        },
        {
            "DomainName": "*.teapot.example.org",
            "CertificateArn": "arn:aws:acm:eu-central-1:123:certificate/3cc5b5f6-2a9d-4716-8da0-d97f15d7610e"
        }
    ]
}

**Comment by lmineiro** [comment]
Any suggestion on how to handle ambiguity?
Let's assume there are multiple matches.
In the case of certificates for `foo.domain.com` and `*.domain.com`, for the ingress `foo.domain.com` we should go with the most specific `foo.domain.com`.
Can there be the case where two certificates matching exactly with the same "weight"? Should we still leave the annotation to specifically choose one in place?

**Comment by hjacobs** [comment]
Yes, we need to keep the annotation anyway (e.g. if there is no hostname matching rule, which is allowed in Ingress).

For multiple certs matching with the same "score": use the cert with the later expiration date. This is also necessary to support cert rotation (old cert still valid, but new cert already uploaded).

**Comment by lmineiro** [comment]
Sounds good to me.

**Comment by hjacobs** [comment]
Fixing this would get rid of the manual step for `zdeploy init --from-senza=..` (https://github.com/zalando-incubator/zalando-deploy-cli/issues/47).

**Comment by szuecs** [comment]
#31 was merged and implemented auto discovery for ACM certificates. It uses the best matched, newest first approach as we discussed this will make it possible to safely update/revoke certificates.

**Comment by szuecs** [comment]
Reopen, because only ACM was done, no IAM certificates.
