### ISSUE TITLE
Updating security group

### ISSUE THREAD

**Issue by flmmartins** [zalando-incubator/kube-ingress-aws-controller#241]
Hello All,

I added some security groups due to AWS limit and add then as source of the main  load balancer security group and the load balancer stopped working.

I then got those new SGs and add then directly to the load balancer (instead using nesting) via AWS GUI configuration and it's still not working so I'm guessing I need to do something with kube-ingress-aws-controller to be aware of those new security groups maybe?

PS: I added the tags necessary in the new SGs

**Comment by szuecs** [comment]
@flmmartins do you see in the logs `Security group ID: <defaultSGID>`? 
Do you have set `zalando.org/aws-load-balancer-security-group: <ingSGID>`? 
What is the SGID of the ALB set to?
Was the CF stack successfully updated?

**Comment by flmmartins** [comment]
> @flmmartins do you see in the logs `Security group ID: <defaultSGID>`?
> Do you have set `zalando.org/aws-load-balancer-security-group: <ingSGID>`?
> What is the SGID of the ALB set to?
> Was the CF stack successfully updated?

I don't have any annotations since they are not in the documentation. Should I add the notation to the Security Groups?

How can I update the CF safely after making changes? Should a to a kubectl replace --force in kube-aws-ingress-controller or go to Amazon CF and click update? What is the recomended approach?


Tks!

**Comment by szuecs** [comment]
> > @flmmartins do you see in the logs `Security group ID: <defaultSGID>`?
> > Do you have set `zalando.org/aws-load-balancer-security-group: <ingSGID>`?
> > What is the SGID of the ALB set to?
> > Was the CF stack successfully updated?
> 
> I don't have any annotations since they are not in the documentation. Should I add the notation to the Security Groups?

No you should not need it.

> 
> How can I update the CF safely after making changes? Should a to a kubectl replace --force in kube-aws-ingress-controller or go to Amazon CF and click update? What is the recomended approach?

The controller will do it for every ingress change, so if you create one, then you can see in the logs that it should do an UpdateStack. You can see it in the CloudFormation Stack in AWS console, that it was updated.

**Comment by flmmartins** [comment]
If I add the annotation would it try to create it first? Or it will just used a previously created one?

**Comment by szuecs** [comment]
I guess the question is answered.

**Comment by flmmartins** [comment]
Does it accept more than one security group like:
zalando.org/aws-load-balancer-security-group: sec1, sec2?

**Comment by szuecs** [comment]
I don’t think so, we should have a more structured setting if this would be a feature we supported.
Please create a separate feature request for that.
