### ISSUE TITLE
Add argument to specify the `resourceLifecycleOwned` value

### ISSUE THREAD

**Issue by MarcusNoble** [zalando-incubator/kube-ingress-aws-controller#252]
https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/0d6be53f9cbcc9cd266bae3d27c9974977e19bda/aws/ec2.go#L43 currently requires that the cluster be tagged as "owned". It is possible that this may also be set to "shared" but will be ignored by kube-ingress-aws-controller with no error or debug messaging explaining why.

I think it'd be useful to be able to provide an override for this value where needed.

**Comment by mikkeloscar** [comment]
Just to understand, what exactly is the use case? When would you have ec2 instances that are shared between clusters?

**Comment by MarcusNoble** [comment]
It's not that the instances are shared, it's that you're running in a shared environment (e.g. there may be another cluster running in the same VPC).

Taken from here: https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html

**Comment by mikkeloscar** [comment]
Sorry, the specific line you linked to is about ec2 instance tags which I think should only be owned by a single cluster even if you have many clusters in one VPC. Unless I missunderstand the EKS docs only the subnets needs to have be `shared`, which is also how we run it and it works fine. The only thing we could maybe allow being `shared` is the security group, but the EC2 and ASGs should stay with the `owned` tag unless EKS doesn't support this for some reason? What do you think?

**Comment by MarcusNoble** [comment]
Yeah, after reading it again I think you're right. I think we must have assumed all values needed to be the same for that key. 

I'll close :)
