### ISSUE TITLE
Regression in CUSTOM_FILTERS >= v0.8.4

### ISSUE THREAD

**Issue by jhohertz** [zalando-incubator/kube-ingress-aws-controller#266]
We have been using the CUSTOM_FILTERS mechanism to isolate a certain set of ASGs as valid for target groups.

Versions >= v0.8.4 no longer honour the CUSTOM_FILTERS specified and instead include all non-master ASGs, resulting in extra, unhealthy hosts in the target groups list.

I haven't had a chance to do deep analysis yet, but the new getOwnedAutoScalingGroups func seems to be at the heart of the issue, and does not consult the filter

**Comment by szuecs** [comment]
@jhohertz did you tested https://github.com/zalando-incubator/kube-ingress-aws-controller/releases/tag/v0.8.11 ?
We fixed one case with the ownership handling in that one.

**Comment by jhohertz** [comment]
I'll have a look and confirm, thanks!

**Comment by jhohertz** [comment]
Unfortunately the regression is still present in 0.8.11

**Comment by jhohertz** [comment]
Haha nope, stymied by the aws sdk being inconsistent.

So at the heart of this, I'll try to explain what's happening:

# Prior to 0.8.4:

* UpdateAutoScalingGroupsAndInstances beings by collecting instance information, filtered by the CUSTOM_FILTERS if specified
* It then builds a list of ASGs *from* the collected instances (which have already been filtered)
* And fetches ASG information for that list
* In other areas, it is fetching instances to pair w/ target groups, based on this list of ASGs

# From 0.8.4 on:

* UpdateAutoScalingGroupsAndInstances beings by collecting instance information, filtered by the CUSTOM_FILTERS if specified
* It then builds a list of "owned" ASGs via the new getOwnedAutoScalingGroups function
** this function is only testing for the default clusterID and lifecycleOwned tags (And does not have any test against the Adapter.manifest.filters)
* And fetches ASG information for that list
* In other areas, it is fetching instances to pair w/ target groups, based on this list of ASGs

So in the prior state, it could not iterate over ASGs NOT matching the CUSTOM_FILTERS, as it discovered the ASGs from a filtered list of instances. In the current state it is directly querying AWS APIs and not applying any filter to the result.

I just need to figure out how to pass the filter into the DescribeAutoScalingGroups call, which seems rather less simple than for instances.

**Comment by szuecs** [comment]
@jhohertz thanks for looking into this issue.
I think I have no time this week to create a PR.
As far as I understand you will work on a PR, so I assign the issue to you. If you don't want to do it, we can take over later, when we have more time.

**Comment by jhohertz** [comment]
I'll see what I can do in the next week. :)

**Comment by mikkeloscar** [comment]
This was fixed in #277
