### ISSUE TITLE
When cloudformation stack is created and/or updated?

### ISSUE THREAD

**Issue by icy** [zalando-incubator/kube-ingress-aws-controller#296]
Hi,

Sometimes I need to update small configuration in controller deployment. Sometimes new cloudformation stack is created and replace the old one. sometimes the stack is just updated. This is confusing, and quite scary when a stack is deleted because it can just bring down the access.

Is the documented somewhere, and how to avoid new stack creation? I only need to update something and reuse of any existing LB would be great choice for transparent and zero-down time mainteance.

Thanks for your reading  and support.

PS: Is that possible to use terraform instead? Terraform has a clean feature to import any existing resources.

Best,

**Comment by mikkeloscar** [comment]
It's not well documented all the cases where this would happen, but we basically set up a new cloudformation stack whenever we can't do an update via cloudformation without respawning the Load Balancer.

The relevant code for deciding this is here: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/worker.go#L72-L123

The general assumption is that you run this project together with external-dns such that it automatically migrates DNS to the new load balancer. We don't just drop a load balancer but give it 30 min. (default) in order to allow DNS migration.

We do not support terraform and also have no plans to do it. It would enable updates where Cloudformation doesn't do it in a non-disruptive way, but it brings other challenges of tracking state etc.

**Comment by icy** [comment]
@mikkeloscar External-dns may be so fast. I got an situation when new balancer was being created and its targets were not ready , but the external-dns had just finished updating all dns entries to new load balancer. Our applications ended up in 50x errors. Is there any way to pause external-dns until new LB is completely ready?

**Comment by jhohertz** [comment]
@icy Which ingress are you running? See if there is an `--update-status` flag available on it, and try setting it to false, as that may be signalling external-dns things are ready before it really is (IE: before this controller had had a chance to set things up)

**Comment by icy** [comment]
@jhohertz I'm using nginx ingress controller, and `--update-status=false` already. The only option I'm thinking now is to delete the external-dns deployment before I roll out any updates on zalando controller. It would great if I know in advance whether new cloudformation stack is created and/or update .

**Comment by jhohertz** [comment]
Hmmm. I am a bit hard pressed to say what is going on then.... sequence of events is generally:

- the ingress (nginx) notices the resource and configures it, but does not signal anything via the use of `--upate=status=false`
- kube-ingress-aws-controller provisions the ALB, mostly caring about any ACM associations it needs to make here really... *IT* then updates the status field of the ingress with the LB target
- only then should external-dns be noticing the ALB target address has changed or is ready, and trigger an update to route53. (IE: that status field *IS* your indication that the DNS is ready to be updated)

**Comment by szuecs** [comment]
@icy do I understand correctly that nginx instances were not available within the time frame of creating a new ALB and switching the traffic via DNS?

In our case we use skipper and the ALB recreation won't change the skipper targets. I wonder if you can change the process to make it reliable.

**Comment by icy** [comment]
@szuecs yes you got it correctly. Today I have to roll out a security patch for system, and after many testinges I come up with this solution https://gist.github.com/icy/20354a9b6962baa2b4df350533751e73 . Next week I will spend time to investigate the behaviors of the controller and/or to provide more technical details .

Thanks and have great weekend.

**Comment by szuecs** [comment]
Why you spawn new nginx-ingress in this case?
If you have the old ones running you would not have a downtime.

**Comment by icy** [comment]
Thanks @szuecs for your time reading and fixing my gist. 

You have a good question. By mistake, the controller in our production infrastructure caught all ingress objects in the cluster. We wanted to limit the effects of that controller,and at the same time, enforced some applications to use another ingress class (See also my security note: https://gist.github.com/icy/52f3fe241994ad54c2519c3447c80355.) The problem sounds easy, but I was so curious to learn how Zalando tools is working, so I tried different options and hence this issue came up ;)

I think it's quite clear now, and I think we can close this ticket. Thanks a lot.

**Comment by szuecs** [comment]
Thanks @icy for coming back!

Your security note gist is correct and some people also use the same pattern for implementing prod/staging/dev environments in the same cluster.
