### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by aryszka** [zalando-incubator/kube-ingress-aws-controller#3]
to support future changes, we can write relatively 'economic' tests the following way:

mock aws and kube. aws can be mocked on the level of the used sdk functions, and the sdk calls can be plugged in the current aws wrapper if it accepts interfaces instead of direct references. mocking the kube api is simpler, it can actually run from an httptest.Server (see https://github.com/zalando/skipper/pull/229/files#diff-a61f8c695fad925c59e28544ef9284faR179)

having the two mocks, we can identify the basic changes that can happen to either aws or kube, e.g. ingress created/deleted or autoscaling groups manually misconfigured. maybe a bad example, but get the point.

having base events, test 2 or 3 happy case scenarios, and the major failure scenarios. This won't bring big coverage, but provides some base, and will make it easy to create tests for future changes/fixes.

**Comment by lmineiro** [comment]
Apart from the ec2metadata (which is by itself relatively easy to mock), for all the other AWS services I've already used the *iface.<foo>API counterparts for exactly that purpose. If the session provided points to a local httptest.Server we get the exact same behavior as for the k8s API.
