### ISSUE TITLE
v0.10.0+ will fail to run if RouteGroups CRD is not installed

### ISSUE THREAD

**Issue by jhohertz** [zalando-incubator/kube-ingress-aws-controller#312]
Recently tried a newer version of this, and found I had to revert because we do not have this CRD installed.

Should this be optional for those continuing to use traditional Ingress records?

**Comment by jhohertz** [comment]
Too funny, looks like you might have addressed this already in a release a few hours ago. :)

**Comment by jhohertz** [comment]
Sort of... Any way to run going forward w/o the CRD?

**Comment by mikkeloscar** [comment]
Sorry about that! IMO we should make it optional with a flag going forward (defaulting to false).

**Comment by szuecs** [comment]
@jhohertz @mikkeloscar I think it should auto detect, if there’s no crd, then don’t try it. The problem is we would have another breaking change if we would have it not enabled as default.
That’s how we addresses it in skipper.
Wdyt?

**Comment by mikkeloscar** [comment]
Auto-detection is fine for me. Considering we did bump the minor version for this change I can see why disabling by default (via flag) would be breaking the other way.
