### ISSUE TITLE
Failed cloudformation provision when singleAZ

### ISSUE THREAD

**Issue by pabloborh** [zalando-incubator/kube-ingress-aws-controller#317]
Im facing with a cloudformation error when it create a LB

> At least two subnets in two different Availability Zones must be specified 

The weird thing is that I've deployed a cluster in single AZ 1/2 weeks ago with kube-ingress-aws-controller and all worked fine. (The LB was created with 3AZ but i only have nodes in one)

Now I'm trying to create other cluster  single AZ and it seems like kube-ingress handle it in a different way. It is possible?

Regards.

**Comment by mikkeloscar** [comment]
Could it be that you had subnets for other AZs which was picked on the initial setup and now you only have a single subnet available?

Regardless we should look into if it can run in a single AZ, or a way to limit the number of AZs

**Comment by pabloborh** [comment]
I have 3 ready subnets. The cluster I'm trying to deploy is similar to the cluster I've deployed, same region, vpc... both singleAZ

**Comment by pabloborh** [comment]
`aws ec2 describe-subnets --filters "Name=vpc-id,Values=vpc-xxxxxx"`
Returns 3 available subnets. But kube-aws-ingress-controller only can see one. I don't know what to check. Can I help you with something? 

Regards.

**Comment by mikkeloscar** [comment]
Does all subnets have the clusterID?

We use this function to filter: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/df00edd03935e68b40d07f265dfeaee4b9236c0c/aws/ec2.go#L155-L208

It expects the tags `kubernetes.io/cluster/<id>` or it falls back to all subnets in case none have a clusterID defined.

**Comment by pabloborh** [comment]
Very thanks @mikkeloscar 
So, If we deploy a singleAZ cluster, we must manually tag at least one more subnet.
