### ISSUE TITLE
Support for AWS WAF v2

### ISSUE THREAD

**Issue by janario** [zalando-incubator/kube-ingress-aws-controller#320]
AWS has build a new version with new feature of WAF, in this case V2

Evaluating the current cloud formation template, when an waf id is provided, it generates something like:

```
WAFAssociation": {
    "Type": "AWS::WAFRegional::WebACLAssociation",
    "Properties": {
        "ResourceArn": {
            "Ref": "LB"
        },
        "WebACLId": "<my-waf-v1-id>"
    },
    "Metadata": {
        "AWS::CloudFormation::Designer": {
            "id": "..."
        }
    }
},
```

Which should be changed in case of WAF v2, something like:
```
"WAF2WAC1KPI3": {
    "Type": "AWS::WAFv2::WebACLAssociation",
    "Properties": {
        "ResourceArn": {
            "Ref": "LB"
        },
        "WebACLId": "<my-waf-v2-id>"
    },
    "Metadata": {
        "AWS::CloudFormation::Designer": {
            "id": "..."
        }
    }
}
```

It would be nice to have a different flag or something to support the waf version 2

* `-aws-waf2-web-acl-id` ?

**Comment by szuecs** [comment]
It should also be possible to set this per ingress, so we need an annotation, too

**Comment by janario** [comment]
Created an MR https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/342

Turns out for waf v2 cloud formation expects an ARN, since the parameter value will be complete different added a condition where when it starts with `arn:aws:wafv2:` it will use waf v2

-aws-waf-web-acl-id

**Comment by janario** [comment]
Closed by #342

**Comment by janario** [comment]
@aryszka 
@mikkeloscar 
@szuecs 

Hi, Can we include this issue or the PR https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/342 in the release?

https://github.com/zalando-incubator/kube-ingress-aws-controller/releases/tag/v0.10.12

Just notice v0.10.12 already contains it
```
$ docker run -it registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.10.12 --help | grep waf
  --aws-waf-web-acl-id=""        WAF
                                 arn:aws:wafv2:<region>:<account>:regional/webacl/<name>/<id>

```

**Comment by szuecs** [comment]
@janario it is already released  in https://github.com/zalando-incubator/kube-ingress-aws-controller/releases/tag/v0.10.11
We have release automation that release every merge to master.

**Comment by janario** [comment]
Oh, that's perfect

Thanks :+1: 

> @janario it is already released in https://github.com/zalando-incubator/kube-ingress-aws-controller/releases/tag/v0.10.11
> We have release automation that release every merge to master.
