### ISSUE TITLE
Shit has hit the fan: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kube-ingress-aws-controller#33]
Ran into this today:

```
zkubectl logs -f app-ingress-controller-4221703179-q8cnq -n kube-system
2017/03/28 07:49:37 found 8 ingress resource(s)
2017/03/28 07:49:37 shit has hit the fan: runtime error: invalid memory address or nil pointer dereference
```

:see_no_evil: 

Docker image is registry.opensource.zalan.do/teapot/kube-aws-ingress-controller:v0.1.1

**Comment by szuecs** [comment]
#36 will provide more insights where it happened

**Comment by mikkeloscar** [comment]
And I suspect it is fixed as part of https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/26#issuecomment-287604880

**Comment by szuecs** [comment]
@hjacobs can we close this, if @mikkeloscar is right it does not make sense to have it open
