### ISSUE TITLE
Log when stack is going to be scheduled for deletion (after cert-ttl)

### ISSUE THREAD

**Issue by ruudk** [zalando-incubator/kube-ingress-aws-controller#347]
I want `kube-ingress-aws-controller` to tell me when it's going to start a timer that will delete a stack. For example, when a new stack gets created, the old stack is scheduled for deletion. It will get the `-cert-ttl` assigned to it, once that hits, the stack is deleted.

But this is nowhere visible in the logs. So you have no idea this is happening, before it's too late.

@mikkeloscar @szuecs Could you point me where this is happening so that I can create a PR?

**Comment by mikkeloscar** [comment]
This is where the ttl is used: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/9844b2cd91be9f64392d4465330b908c92609b90/worker.go#L156
