### ISSUE TITLE
Host+Path+Regex integrated redirect rule

### ISSUE THREAD

**Issue by alvaro-qwantec** [zalando-incubator/kube-ingress-aws-controller#355]
Hi, recently I start using "kube-ingress-aws-controller" in my cluster k8s. A while ago I was using a Nginx server and I used the next redirect rule with success:

```
server {
    listen 80;
    listen 443 http2 ssl;
    server_name ~^(?<subdomain>\w+)\.example\.com$;
    location / {
        return 301 https://example.com/app/$subdomain;
    }
}
```

Is like a combination between modRequestHeader with modPath and Regex, and involves the entire request URL.

My question is, How can I do the same thing with skipper annotations in my ingress yaml?

**Comment by szuecs** [comment]
@alvaro-qwantec please file an issue to https://github.com/zalando/skipper/issues, thanks. We will answer it there.
