### ISSUE TITLE
Add example yamls on how to test it. 

### ISSUE THREAD

**Issue by Raffo** [zalando-incubator/kube-ingress-aws-controller#37]
We should provide example yamls for an application for the end user to test this in the suggested scenario.

**Comment by hjacobs** [comment]
What is this about?

**Comment by Raffo** [comment]
@hjacobs it's just a note while talking with a possible interested user... how do I test that it works? Sorry for creating an issue with not so much information, I was on the move.

**Comment by szuecs** [comment]
@Raffo If everything works you should see in the status field of your ingress object. The yaml files to create an ingress are in the README section "Creating Load Balancers" and the deployment of this controller can be found in https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/
What do you think is required to close this issue?

**Comment by Raffo** [comment]
Maybe a full example folder with yamls to test it and an explanation of what is the expected result?
