### ISSUE TITLE
kube-ingress-aws on EKS fargate possible?

### ISSUE THREAD

**Issue by wilkej** [zalando-incubator/kube-ingress-aws-controller#375]
Hello,

we are using the kube-ingress-aws-controller with AWS EKS on self-managed EC2 Instances. I started to evaluate AWS EKS fargate and tried to deploy kube-ingress-aws with IAM instance profile for service accounts (IRSA).

I get the error in the log files: 

`time="2020-10-05T08:02:04Z" level=info msg="starting /kube-ingress-aws-controller v0.11.7"`  
`time="2020-10-05T08:06:05Z" level=fatal msg="RequestError: send request failed caused by: Get "http://169.254.169.254/latest/meta-data/instance-id\": dial tcp 169.254.169.254:80: i/o timeout" stream closed `

Does anyone has a similar setup running? Is this something that can work?

**Comment by mikkeloscar** [comment]
I don't know fargate well, but it makes sense that it would not have the same interface e.g. access to the metadata service like on a plain EC2 instance.

Currently the controller expects to run on an EC2 instance, however I believe we should make it possible to avoid this dependency e.g. by letting the user provide the needed configuration via flags.

So in short, it's not currently possible it would seems, but we're open to make it possible.

**Comment by wilkej** [comment]
Thank you for the quick response and the clarification. 

Unfortunately I don't have GO experience to look into it. I think it depends on how the AWS Client is configured. The team developing external dns uses assume role with webidentity. This works fine in EKS fargate.

**Comment by mikkeloscar** [comment]
> Unfortunately I don't have GO experience to look into it. I think it depends on how the AWS Client is configured. The team developing external dns uses assume role with webidentity. This works fine in EKS fargate.

It's slightly different than this because it's not just about getting the AWS credentials. We additionally use the meta data to get the current instance-id and then looking tags of that instance. All of this could be passed via flags to this is not needed and the controller would not have to run on an EC2 instance.

**Comment by szuecs** [comment]
@wilkej would you mind figuring out if there is a metadata endpoint in fargate?
Maybe there is, if not we can do what @mikkeloscar suggests and add some flags to be passed by the user.
It's not much code, but maybe we can have it more easy and just pass a different URL for metadata endpoint.

**Comment by wilkej** [comment]
@szuecs I'll check. I found this blog post indicating that the meta data service v1 isn't working on fargate.
https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-supports-ec2-instance-metadata-service-v2/

I tried to get metadata as described in the AWS documentation but the curl doesn't get a response. I'm not quite sure what the issue is. I have to dig deeper on this.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

**Comment by wilkej** [comment]
I just realized the post is regarding EKS supporting Metadata Service v2 in general. Nothing about Fargate is mentioned. I opened an AWS support ticket to get a official answer

**Comment by wilkej** [comment]
I got the confirmation from AWS that the Metadata service isn't available in fargate.

`You are correct in that it isn't possible to access the EC2 instance metadata service from a container running on Fargate. This is due to tightened security rules for Fargate.`

**Comment by szuecs** [comment]
@wilkej thanks great input!

**Comment by mikkeloscar** [comment]
@wilkej I created a PR to allow not depending running on EC2 instances: https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/376

Would appreciate if you could help us test that it fixes the issue with fargate. The image built from the PR is: `registry.opensource.zalan.do/teapot/kube-ingress-aws-controller-test:pr-376-2` you need to supply `--cluster-id` and `--vpc-id` when starting the controller.

**Comment by wilkej** [comment]
Good Morning @mikkeloscar I launched the kube-ingress-aws-controller and I didn't get any error messages anymore. The SG discovery worked as well. 

I couldn't test the if the loadbalancer will be created as I don't have certificates available in the environment (yet). 

A side from this is look fine for me. Thank you

**Comment by szuecs** [comment]
Fix will be released in https://github.com/zalando-incubator/kube-ingress-aws-controller/releases/tag/v0.11.12
