### ISSUE TITLE
Use existing Application Load Balancer

### ISSUE THREAD

**Issue by ddezoysa** [zalando-incubator/kube-ingress-aws-controller#396]
How to configure kube-ingress-aws-controller to use existing ALB rather than provisioning the ALB again through the controller?

In an enterprise environment, entire infrastructure is provisioned through Infrastructure as code such as Terraform. As the ALB is provisioned outside the main terraform stack it is unable to manage the ALB and unable to continue the next level of configurations such as CloudFront, Route53 configurations which require ALB ID provisioned by kube-ingress-aws-controller as a manual input.

If this feature is already available, please share the documentation or else appreciate it if this feature can be implemented to pass the existing ALB ID as flags to the controller. Ex: --alb-id=xxxx

**Comment by mikkeloscar** [comment]
This is not something currently supported as the controller assumes full control of the ALBs that it manages and assumes they're managed via Cloudformation.
It would be quite a different model to support what you request so it's unlikely we will support it here.

**Comment by szuecs** [comment]
I agree with @mikkeloscar , this controller exist to manage the lifecycle of the ALB/NLB via CF.
