### ISSUE TITLE
Can't provision load-balancer for Fargate pods in cluster

### ISSUE THREAD

**Issue by d-wire** [zalando-incubator/kube-ingress-aws-controller#408]
I've been trying to transition our existing architecture from using the AWS provided load-balancer controller to this one. Our existing cluster runs a few EC2 instances as worker nodes and all of our services and deployments are running in Fargate pods. I followed the deployment instructions provided (hopefully correctly), but for some reason when I create new ingresses, no load-balancer gets provisioned and no logs are created within the kube-ingress-aws-controller pod. So I was wondering if this ingress-controller is even supposed to work with Fargate pods or if this is strictly for EC2 instances, since I didn't see any reference to Fargate in the documentation.

**Comment by jonathanbeber** [comment]
Hello, @d-wire. IIRC we don't have any cluster running with Fargate, so we don't have experience with that. At the same time, it's strange that you don't have any logs in the controller. Do you see at least initialization logs? 

Atm, I don't see an impeditive for Fargate but I don't have experience with it. You can also try running it with `--debug`.

**Comment by d-wire** [comment]
Hi @jonathanbeber. I did get some initialization log of:
time="2021-03-22T18:49:58Z" level=info msg="starting /kube-ingress-aws-controller v0.11.21"
And I did manage to trigger a log to be generated when adding an ingress that said
time="2021-03-22T18:53:59Z" level=fatal msg="RequestError: send request failed\ncaused by: Get \"http://169.254.169.254/latest/meta-data/instance-id\": dial tcp 169.254.169.254:80: i/o timeout"
This then caused a CrashLoop in the ingress controller pod. However, this only happened occasionally when creating an ingress. In general, I would create the ingress, see that no address was associated with it, check the logs, and only see the initialization message.

**Comment by mikkeloscar** [comment]
@d-wire does the `kube-ingress-aws-controller` run on EC2 or on fargate? By default it assumes it runs on EC2 and will lookup details like cluster ID and VPC ID from the EC2 instance where it's runnning. This information can also be passed on startup via flags if it's not running on EC2 (`--cluster-id`, `--vpc-id`).

The specific error you get seems to indicate that the controller is not getting any AWS credentials. How to set this up correctly depends on the environment, but since you're on EKS you could look into this method: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by d-wire** [comment]
@mikkeloscar it runs on Fargate. This seems to be a crucial piece I was missing though. It's now generating logs and seems to be trying to do its job. Only now it says:
`time="2021-03-23T13:48:37Z" level=error msg="doWork failed to list ingress resources: failed to get ingress list: no permission to access resource"`
which seems to be just some IAM permission that I'm missing.

**Comment by mikkeloscar** [comment]
This is related to RBAC permissions. You can find the required ones here: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/ingress-serviceaccount.yaml

**Comment by d-wire** [comment]
Ah I had it set to use the wrong ingress-api-version. Setting that fixed the RBAC issue. It now generates logs about finding certs and creating stacks. It still doesn't seem to be able to provision the load-balancer though. It will appear on the ELB page of the AWS console with a status of provisioning, then just disappear a few seconds later. Not sure where to go to find the logs for what's happening either since nothing seems to be making it to CloudWatch during the provisioning phase.

**Comment by d-wire** [comment]
That was indeed the issue. The IAM role was missing the permission ModifyTargetGroupAttributes. Not sure if this is specific to my use-case, but that permission may be missing from the documentation at https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/requirements.md. Thanks so much for the help!

**Comment by mikkeloscar** [comment]
@d-wire Could you share the error from cloudformation related to this permission? We don't have it in our production config for 180 clusters and I have never seen this issue, so I would be curious under which condition it's needed.

**Comment by mikkeloscar** [comment]
Thanks! Will update the docs with the missing permission #410.

Turns out we already have this enabled in our production configuration, I just missed it before.
