### ISSUE TITLE
Application Load Balancers created without any listeners (inconsistent state?)

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kube-ingress-aws-controller#41]
** EDIT: I first suspected just logging, but now it looks like a problem with the non-atomic ALB creation process**

I see a lot of repeated log lines (in the same second!) which are not necessary (they only tell me that there is some ALB without certs which is totally fine):

```
2017/03/28 19:03:04 load balancer ARN "arn:aws:elasticloadbalancing:eu-central-1:123456133479:loadbalancer/app/3479-eu-central-1-kube-1-9295a7c/881340b3111ae953" has no certificates
2017/03/28 19:03:05 load balancer ARN "arn:aws:elasticloadbalancing:eu-central-1:123456133479:loadbalancer/app/3479-eu-central-1-kube-1-6037b91/b0c3408af295cac7" has no certificates
2017/03/28 19:03:05 load balancer ARN "arn:aws:elasticloadbalancing:eu-central-1:123456133479:loadbalancer/app/3479-eu-central-1-kube-1-9295a7c/881340b3111ae953" has no certificates
2017/03/28 19:03:05 load balancer ARN "arn:aws:elasticloadbalancing:eu-central-1:123456133479:loadbalancer/app/3479-eu-central-1-kube-1-6037b91/b0c3408af295cac7" has no certificates
2017/03/28 19:03:05 load balancer ARN "arn:aws:elasticloadbalancing:eu-central-1:123456133479:loadbalancer/app/3479-eu-central-1-kube-1-9295a7c/881340b3111ae953" has no certificates
2017/03/28 19:03:05 load balancer ARN "arn:aws:elasticloadbalancing:eu-central-1:123456133479:loadbalancer/app/3479-eu-central-1-kube-1-6037b91/b0c3408af295cac7" has no certificates
2017/03/28 19:03:05 load balancer ARN "arn:aws:elasticloadbalancing:eu-central-1:123456133479:loadbalancer/app/3479-eu-central-1-kube-1-9295a7c/881340b3111ae953" has no certificates
2017/03/28 19:03:05 load balancer ARN "arn:aws:elasticloadbalancing:eu-central-1:123456133479:loadbalancer/app/3479-eu-central-1-kube-1-6037b91/b0c3408af295cac7" has no certificates
```

FYI: the cluster has 8 Ingress resources and it's running v0.1.2 (registry.opensource.zalan.do/teapot/kube-aws-ingress-controller:v0.1.2).

**Comment by hjacobs** [comment]
Actually the log lines might be a hint for a potential bug: the two mentioned ALBs have no listeners at all!

**Comment by hjacobs** [comment]
I suspect some error happened during the ALB creation process (https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/aws/alb.go#L99) and the listeners were never created.

The process is not atomic and might lead to such inconsistencies...

**Comment by lmineiro** [comment]
Indeed, it's true that the current approach is not atomic and there was never a decision how to handle failure of creating any subsequent resources.

We should explore using CloudFormation to create managed ALBs.

**Comment by szuecs** [comment]
Was done by #54 #57 #56 
release version >= v0.3.0
