### ISSUE TITLE
Issue with kubernetes 1.17

### ISSUE THREAD

**Issue by lambertpan** [zalando-incubator/kube-ingress-aws-controller#417]
I upgraded the kubernetes (eks) cluster from 1.16 to 1.17, and for any newly created ingress the status is not getting updated. I don't see any errors in the log. I appreciate any help on this.
I used the following version registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.9.8 and tried to update to latest version along with new roles. ( as mentioned here https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/kube-ingress-aws.md) But no use.

**Comment by mikkeloscar** [comment]
Can you share the logs of the controller? Even if you don't see any errors it might indicate what could be going on.

**Comment by lambertpan** [comment]
I see an error, could this be an issue?
level=error msg="updateStack(map[\"arn:aws:acm:us-west-2:175410366012:certificate/3d266fff-34aa-4f06-9ed9-a09a8d52a360\":\"2021-04-22 10:48:08.127353002 +0000 UTC\" \"arn:aws:acm:us-west-2:175410366012:certificate/58c2c7f4-8ade-40a9-87c2-cb392c6c2db6\":\"0001-01-01 00:00:00 +0000 UTC\" \"arn:aws:acm:us-west-2:175410366012:certificate/bff86325-8d13-4102-acd1-7adebdf01bc9\":\"0001-01-01 00:00:00 +0000 UTC\" \"arn:aws:acm:us-west-2:175410366012:certificate/d868cc8b-be68-43d4-a038-10190e8f1fd0\":\"0001-01-01 00:00:00 +0000 UTC\"]) failed: ValidationError: Stack:arn:aws:cloudformation:us-west-2:175410366012:stack/kube-ingress-aws-controller-terraform-eks-dev-oregon-shared-46da18fc-564a-48d1-b28b-06b294f08945/8dc4ea50-7746-11ea-b521-0259df39583c is in UPDATE_ROLLBACK_FAILED state and can not be updated.\n\tstatus code: 400, request id: 8a300c64-acff-4007-ac5e-da5a84569e55"

**Comment by mikkeloscar** [comment]
Yup definitely, the you need to look at the cloudformation stack events to understand what failed, this is not exposed in the controller itself.

**Comment by lambertpan** [comment]
Thanks for your help; I will check that

**Comment by lambertpan** [comment]
Fixing the cloudformation issue made the ingress work again. Thanks for the prompt response. The certificates got auto renewed but somehow the ingress-controller couldn't update it.
