### ISSUE TITLE
In EKS: I cant set permission to access to ingress

### ISSUE THREAD

**Issue by luismanuelmontoro** [zalando-incubator/kube-ingress-aws-controller#419]
Kube-ingress-aws-controller pod has this error:

doWork failed to list ingress resources: failed to get ingress list: no permission to access resource

I try to add the grants that i saw in the readme, and didn´t work.

**Comment by szuecs** [comment]
I guess you use RBAC in your cluster?
Can you show the role and RBAC that is assigned to kube-ingress-aws-controller pod?

**Comment by luismanuelmontoro** [comment]
`apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ingress-aws
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-controller
rules:
- apiGroups: # only one of extensions, networking.k8s.io is needed depending on the --ingress-api-version flag
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups: # only one of extensions, networking.k8s.io is needed depending on the --ingress-api-version flag
  - extensions
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - zalando.org
  resources:
  - routegroups
  verbs:
  - get
  - list
- apiGroups:
  - zalando.org
  resources:
  - routegroups/status
  verbs:
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-controller
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: kube-ingress-aws
  namespace: kube-system
`

**Comment by luismanuelmontoro** [comment]
I think my problem is "kube-ingress-aws-controller" don't create me a load-balancer in EKS. Can you help me?

**Comment by mikkeloscar** [comment]
Please share the full logs of the `kube-ingress-aws-controller`. Otherwise it's hard to understand what may be going on.

**Comment by mikkeloscar** [comment]
@luismanuelmontoro Do you have `serviceAccountName: name: kube-ingress-aws` on your deployment of the ingress-controller?

**Comment by luismanuelmontoro** [comment]
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ingress-aws-controller
  namespace: kube-system
  labels:
    application: kube-ingress-aws-controller
    component: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-ingress-aws-controller
      component: ingress
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::xxxxxxxxxxx:role/kube-ingress-aws-controller
      labels:
        application: kube-ingress-aws-controller
        component: ingress
    spec:
      serviceAccountName: aws-ingress-controller
      containers:
      - name: controller
        image: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:latest
        env:
        - name: AWS_REGION
          value: xxxxxxxx`
          
    `apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-ingress-controller
rules:
- apiGroups: # only one of extensions, networking.k8s.io is needed depending on the --ingress-api-version flag
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups: # only one of extensions, networking.k8s.io is needed depending on the --ingress-api-version flag
  - extensions
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - zalando.org
  resources:
  - routegroups
  verbs:
  - get
  - list
- apiGroups:
  - zalando.org
  resources:
  - routegroups/status
  verbs:
  - patch
  - update`

**Comment by luismanuelmontoro** [comment]
I named in each file as: aws-ingress-controller is this a problem??

**Comment by mikkeloscar** [comment]
The name doesn't matter as long as it's consistent. From what you posted I can't verify that the RBAC binding is correct.

**Comment by jonathanbeber** [comment]
@luismanuelmontoro did you change your `ClusterRoleBinding` resource to match the new name?

Because, [here in your comment](https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/419#issuecomment-850247893), the binding is done for a `ServiceAccount` named `kube-ingress-aws` instead of `aws-ingress-controller`.

**Comment by luismanuelmontoro** [comment]
Yes like this:

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-ingress-controller
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: kube-ingress-aws
  namespace: kube-system

**Comment by luismanuelmontoro** [comment]
When i open the logs in skipper shows me:

error while receiveing initial data;failed to load cluster state: request failed, status: 403, 403 Forbidden

**Comment by luismanuelmontoro** [comment]
I solved changing the name https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/419#issuecomment-850408945 tolds

> 
> 
> @luismanuelmontoro Do you have `serviceAccountName: name: kube-ingress-aws` on your deployment of the ingress-controller?
