### ISSUE TITLE
Make multi-arch images publicly available

### ISSUE THREAD

**Issue by spr-mweber3** [zalando-incubator/kube-ingress-aws-controller#562]
Hey there, I'd like to know why the multi-arch images that you build are not made publicly available? We'd like to utilize them in our mixed amd64/arm64 setup without having to worry what image with which tag gets deployed where.

Is there any specific reason why you're not storing the multi-arch images in the same registry as your other images?

([ref](https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/delivery.yaml#L67))

**Comment by szuecs** [comment]
@spr-mweber3  the problem is that our opensource registry does not support multi-arch containers

Maybe we can push it to some other free registry, but I don't know if something like this exists.

**Comment by spr-mweber3** [comment]
GitHub Container Registry (ghcr.io) [supports multi-arch images](https://github.blog/changelog/2020-09-17-github-container-registry-support-for-multi-arch-images/) for almost two years now. Maybe this could be an option for you? I think it makes perfectly sense since you're hosting the code here already, too.

It's pretty straight-forward to set-up.

**Comment by spr-mweber3** [comment]
@szuecs Currently @MustafaSaber is on that matter for the `skipper` delivery and making progress. I suppose when a solution is ready there, it can be easily taken over to the `kube-ingress-aws-controller` delivery process.
