### ISSUE TITLE
ALBs are reused across clusters in the same account

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kube-ingress-aws-controller#6]
when ALBs are configured with the same cert they are supposed to be reused. currently it seems that they are reused across clusters as well. this might lead to problems as two clusters have different target groups. needs to be confirmed.

**Comment by lmineiro** [comment]
The collision is a know limitation and it's mostly due to the naming convention for the created AWS resources (ALB and TargetGroup).

We'll switch this to use the cluster ID and a fragment of the cert arn.
