### ISSUE TITLE
Feature request: Deregister terminating nodes from ALB to avoid 5xx errors

### ISSUE THREAD

**Issue by adri** [zalando-incubator/kube-ingress-aws-controller#604]
**Is your feature request related to a problem? Please describe.**
We've noticed in our production environment that we have a need for something to deregister nodes from load balancers as part of the draining procedure, before the instance is terminated. 

We were using `cluster-autoscaler` (based on auto-scaling groups) in combination with [`lifecycle-manager`](https://github.com/keikoproj/lifecycle-manager) for this. Recently we switched to Karpenter, which doesn't require auto-scaling groups (ASG). Since there is no ASG lifecycle hook to wait for the ALB to drain connections to the node before terminating it, we see 5xx errors when nodes terminate before it's deregistered from an ALB.

**Describe the solution you would like**
Since this [PR](https://github.com/aws/karpenter/pull/2518) Karpenter adds a node label `node.kubernetes.io/exclude-from-external-load-balancers` when a node is going to shut down.

The behavior we're looking for is that `kube-ingress-aws-controller` would react to this label being added, sends a deregistration request and then waits for the deregistration to finish before marking the instance as being ready to terminate (if possible).

**Describe alternatives you've considered (optional)**
We're considering writing our own script to remove instance tags from the EC2 instance that `kube-ingress-aws-controller` uses to filter nodes that are added to the ALB.

**Comment by szuecs** [comment]
Maybe we should also switch :)

@universam1 ^
A happy user.

**Comment by universam1** [comment]
We run that very setup exclusively and consider it stable. 👍
