### ISSUE TITLE
safely delete stacks

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/kube-ingress-aws-controller#68]
While renewing certificates we saw that the ALB CF stack was deleted too fast, such that DNS was not switched so DNS pointing to the deleted ALB. This will be a problem for all ALB switching processes.

We propose to TAG orphaned stacks to be deleted with a timestamp and delete it if this is TAGed longer than 1 hour for example.

**Comment by hjacobs** [comment]
Sounds like a plan :smile:

**Comment by szuecs** [comment]
fixed
