### ISSUE TITLE
Enable different levels of logging

### ISSUE THREAD

**Issue by AndreaGiardini** [zalando-incubator/kube-ingress-aws-controller#89]
I haven't found a way to select different levels of logging

Right now the controller prints its status and information every time it polls the resources.
Would be nice to have a flag to select the desired logging level

In my case, for example, I would like to log only when the controller detects a change. Does this proposal make sense to you?

**Comment by mikkeloscar** [comment]
@AndreaGiardini Yup, this makes a lot of sense, is it something you would be willing to implement? :)

**Comment by AndreaGiardini** [comment]
I will have a look at it as soon as I have a bit of spare time :)

**Comment by szuecs** [comment]
@AndreaGiardini If you do then please do it quiet by default and add a --debug flag.

**Comment by flmmartins** [comment]
Hello All,
I see that the PR is still open. Any update when it will be merged?

**Comment by szuecs** [comment]
As soon as someone will resolve the conflicts, I will review it again.
Right now, it has no priority from my side.
