### ISSUE TITLE
Implement Adapter also for Kubernetes

### ISSUE THREAD

**Issue by lmineiro** [zalando-incubator/kube-ingress-aws-controller#9]
Currently all the AWS operations are encapsulated in its own Adapter while the Kubernetes operations are directly exported.

For a cleaner design the Kubernetes operations should have a similar Adapter.

**Comment by Raffo** [comment]
You would obviously need to rename a couple of things. I was about to attempt a refactor to have a configurable port, but better have the two things done together probably. Let's discuss it together offline.

**Comment by lmineiro** [comment]
Closed with #20
