### ISSUE TITLE
support semi-automatic SAN cert lookup

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/kube-ingress-aws-controller#92]
Follow up from #81

We should support a list of alternative names that should be covered:

    metadata:
      name: myingress
      annotations:
        zalando.org/aws-load-balancer-ssl-cert-domain: 
        - *.example.org
        - test-app.example.com

Certificate lookup has to find all of them. 

Keep in mind that this has nothing to do with DNS. https://github.com/kubernetes-incubator/external-dns will not use this annotation. It will lookup what to do from the spec hostname:

    spec:
      rules:
      - host: test-app.example.org
      - host: test-app.example.com

If you want to have an overview what reads/writes what https://www.slideshare.net/SandorSzuecs/2017-0719-automatic-infrastructure-for-kubernetes-ingress-in-aws last slides will show the ingress stack.

**Comment by mikkeloscar** [comment]
@szuecs is this still relevant after #143 ?

**Comment by szuecs** [comment]
no
