### ISSUE TITLE
AWS Application Load Balancers Now Support Multiple TLS Certificates (SNI)

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kube-ingress-aws-controller#94]
AWS now added SNI support for ALB. The ingress controller currently creates one ALB per certificate. We should update the ingress controller to create one ALB for multiple TLS certificates (if this is desired, maybe configurable?): https://aws.amazon.com/blogs/aws/new-application-load-balancer-sni/

**Comment by szuecs** [comment]
Example cli call showing which data is required

    aws elbv2 add-listener-certificates --listener-arn <listener-arn> --certificates CertificateArn=<cert-arn>
